/**
 * AUTO-GENERATED by `scripts/render-trial-audio.mjs`. Do not edit by hand —
 * the script rewrites this file wholesale from whatever mp3s exist under
 * `assets/audio/trial/`.
 *
 * It is generated rather than written because Metro's `require` must be a
 * static string literal it can see at build time, so the map cannot be built
 * by walking the directory at runtime — and because a clip that has not been
 * rendered yet must simply be absent, not a `require` of a missing file
 * (which fails the bundle, not just the exercise).
 *
 * An empty map is the correct committed state until the clips are rendered:
 * `resolveTrialAudio` returns null for every key and every pack degrades to
 * its text-only exercises. See `spec.ts` for why that fallback matters.
 */
import { Asset } from 'expo-asset';

/**
 * `${lang}/${topic}/${w1|w2|w3|sentence}` → the Metro module id for its clip.
 *
 * Example of a generated entry:
 *   'es/travel/w1': require('../../../assets/audio/trial/es/travel/w1.mp3'),
 */
const TRIAL_AUDIO_MODULES: Record<string, number> = {
  // --- generated entries go here ---
};

/**
 * Resolve a bundled trial clip to a URI expo-av can play, or null when the
 * clip has not been rendered.
 *
 * `localUri` is preferred: in a release build the asset has been copied into
 * the app container and that is a `file://` path, which plays without the
 * network. `uri` is the dev-server fallback.
 */
export function resolveTrialAudio(audioKey: string): string | null {
  const moduleId = TRIAL_AUDIO_MODULES[audioKey];
  if (moduleId === undefined) return null;

  try {
    const asset = Asset.fromModule(moduleId);
    return asset.localUri ?? asset.uri ?? null;
  } catch {
    // A clip that cannot be resolved is a missing clip: the pack falls back to
    // its text-only exercise rather than handing the runner a broken URI.
    return null;
  }
}

/** Every key the manifest currently has a clip for. Used by the tests. */
export function bundledTrialAudioKeys(): string[] {
  return Object.keys(TRIAL_AUDIO_MODULES);
}
