/**
 * AUTO-GENERATED by `scripts/render-trial-audio.mjs`. Do not edit by hand —
 * the script rewrites this file wholesale from whatever mp3s exist under
 * `assets/audio/trial/`.
 *
 * It is generated rather than written because Metro's `require` must be a
 * static string literal it can see at build time, so the map cannot be built
 * by walking the directory at runtime — and because a clip that has not been
 * rendered yet must simply be absent, not a `require` of a missing file
 * (which fails the bundle, not just the exercise).
 *
 * An empty map is the correct committed state until the clips are rendered:
 * `resolveTrialAudio` returns null for every key and every pack degrades to
 * its text-only exercises. See `spec.ts` for why that fallback matters.
 */
import { Asset } from 'expo-asset';

/**
 * `${lang}/${topic}/${w1|w2|w3|sentence}` → the Metro module id for its clip.
 *
 * Example of a generated entry:
 *   'es/travel/w1': require('../../../assets/audio/trial/es/travel/w1.mp3'),
 */
const TRIAL_AUDIO_MODULES: Record<string, number> = {
  'es/travel/w1': require('../../../assets/audio/trial/es/travel/w1.mp3'),
  'es/travel/w2': require('../../../assets/audio/trial/es/travel/w2.mp3'),
  'es/travel/w3': require('../../../assets/audio/trial/es/travel/w3.mp3'),
  'es/travel/sentence': require('../../../assets/audio/trial/es/travel/sentence.mp3'),
  'es/family/w1': require('../../../assets/audio/trial/es/family/w1.mp3'),
  'es/family/w2': require('../../../assets/audio/trial/es/family/w2.mp3'),
  'es/family/w3': require('../../../assets/audio/trial/es/family/w3.mp3'),
  'es/family/sentence': require('../../../assets/audio/trial/es/family/sentence.mp3'),
  'es/work/w1': require('../../../assets/audio/trial/es/work/w1.mp3'),
  'es/work/w2': require('../../../assets/audio/trial/es/work/w2.mp3'),
  'es/work/w3': require('../../../assets/audio/trial/es/work/w3.mp3'),
  'es/work/sentence': require('../../../assets/audio/trial/es/work/sentence.mp3'),
  'es/media_culture/w1': require('../../../assets/audio/trial/es/media_culture/w1.mp3'),
  'es/media_culture/w2': require('../../../assets/audio/trial/es/media_culture/w2.mp3'),
  'es/media_culture/w3': require('../../../assets/audio/trial/es/media_culture/w3.mp3'),
  'es/media_culture/sentence': require('../../../assets/audio/trial/es/media_culture/sentence.mp3'),
  'es/housing_admin/w1': require('../../../assets/audio/trial/es/housing_admin/w1.mp3'),
  'es/housing_admin/w2': require('../../../assets/audio/trial/es/housing_admin/w2.mp3'),
  'es/housing_admin/w3': require('../../../assets/audio/trial/es/housing_admin/w3.mp3'),
  'es/housing_admin/sentence': require('../../../assets/audio/trial/es/housing_admin/sentence.mp3'),
  'fr/travel/w1': require('../../../assets/audio/trial/fr/travel/w1.mp3'),
  'fr/travel/w2': require('../../../assets/audio/trial/fr/travel/w2.mp3'),
  'fr/travel/w3': require('../../../assets/audio/trial/fr/travel/w3.mp3'),
  'fr/travel/sentence': require('../../../assets/audio/trial/fr/travel/sentence.mp3'),
  'fr/family/w1': require('../../../assets/audio/trial/fr/family/w1.mp3'),
  'fr/family/w2': require('../../../assets/audio/trial/fr/family/w2.mp3'),
  'fr/family/w3': require('../../../assets/audio/trial/fr/family/w3.mp3'),
  'fr/family/sentence': require('../../../assets/audio/trial/fr/family/sentence.mp3'),
  'fr/work/w1': require('../../../assets/audio/trial/fr/work/w1.mp3'),
  'fr/work/w2': require('../../../assets/audio/trial/fr/work/w2.mp3'),
  'fr/work/w3': require('../../../assets/audio/trial/fr/work/w3.mp3'),
  'fr/work/sentence': require('../../../assets/audio/trial/fr/work/sentence.mp3'),
  'de/travel/w2': require('../../../assets/audio/trial/de/travel/w2.mp3'),
  'pt/travel/w3': require('../../../assets/audio/trial/pt/travel/w3.mp3'),
  'pt/travel/sentence': require('../../../assets/audio/trial/pt/travel/sentence.mp3'),
  'pt/family/w1': require('../../../assets/audio/trial/pt/family/w1.mp3'),
  'pt/family/w2': require('../../../assets/audio/trial/pt/family/w2.mp3'),
  'pt/family/w3': require('../../../assets/audio/trial/pt/family/w3.mp3'),
  'pt/family/sentence': require('../../../assets/audio/trial/pt/family/sentence.mp3'),
  'pt/work/w1': require('../../../assets/audio/trial/pt/work/w1.mp3'),
  'pt/work/w2': require('../../../assets/audio/trial/pt/work/w2.mp3'),
  'pt/work/w3': require('../../../assets/audio/trial/pt/work/w3.mp3'),
  'pt/work/sentence': require('../../../assets/audio/trial/pt/work/sentence.mp3'),
  'pt/media_culture/w1': require('../../../assets/audio/trial/pt/media_culture/w1.mp3'),
  'pt/media_culture/w2': require('../../../assets/audio/trial/pt/media_culture/w2.mp3'),
  'pt/media_culture/w3': require('../../../assets/audio/trial/pt/media_culture/w3.mp3'),
  'pt/media_culture/sentence': require('../../../assets/audio/trial/pt/media_culture/sentence.mp3'),
  'pt/housing_admin/w1': require('../../../assets/audio/trial/pt/housing_admin/w1.mp3'),
  'pt/housing_admin/w2': require('../../../assets/audio/trial/pt/housing_admin/w2.mp3'),
  'pt/housing_admin/w3': require('../../../assets/audio/trial/pt/housing_admin/w3.mp3'),
  'pt/housing_admin/sentence': require('../../../assets/audio/trial/pt/housing_admin/sentence.mp3'),
  'ja/travel/w1': require('../../../assets/audio/trial/ja/travel/w1.mp3'),
  'ja/travel/w2': require('../../../assets/audio/trial/ja/travel/w2.mp3'),
  'ja/travel/w3': require('../../../assets/audio/trial/ja/travel/w3.mp3'),
  'ja/travel/sentence': require('../../../assets/audio/trial/ja/travel/sentence.mp3'),
  'ja/family/w1': require('../../../assets/audio/trial/ja/family/w1.mp3'),
  'ja/family/w2': require('../../../assets/audio/trial/ja/family/w2.mp3'),
  'ja/family/w3': require('../../../assets/audio/trial/ja/family/w3.mp3'),
  'ja/family/sentence': require('../../../assets/audio/trial/ja/family/sentence.mp3'),
  'ja/work/w1': require('../../../assets/audio/trial/ja/work/w1.mp3'),
  'ja/work/w2': require('../../../assets/audio/trial/ja/work/w2.mp3'),
  'ja/work/w3': require('../../../assets/audio/trial/ja/work/w3.mp3'),
  'ja/work/sentence': require('../../../assets/audio/trial/ja/work/sentence.mp3'),
  'ja/media_culture/w1': require('../../../assets/audio/trial/ja/media_culture/w1.mp3'),
  'ja/media_culture/w2': require('../../../assets/audio/trial/ja/media_culture/w2.mp3'),
  'ja/media_culture/w3': require('../../../assets/audio/trial/ja/media_culture/w3.mp3'),
  'ja/media_culture/sentence': require('../../../assets/audio/trial/ja/media_culture/sentence.mp3'),
  'ja/housing_admin/w1': require('../../../assets/audio/trial/ja/housing_admin/w1.mp3'),
  'ja/housing_admin/w2': require('../../../assets/audio/trial/ja/housing_admin/w2.mp3'),
  'ja/housing_admin/w3': require('../../../assets/audio/trial/ja/housing_admin/w3.mp3'),
  'ja/housing_admin/sentence': require('../../../assets/audio/trial/ja/housing_admin/sentence.mp3'),
  'ko/travel/w1': require('../../../assets/audio/trial/ko/travel/w1.mp3'),
  'ko/travel/w2': require('../../../assets/audio/trial/ko/travel/w2.mp3'),
  'ko/family/w1': require('../../../assets/audio/trial/ko/family/w1.mp3'),
  'ko/family/w3': require('../../../assets/audio/trial/ko/family/w3.mp3'),
  'ko/work/w2': require('../../../assets/audio/trial/ko/work/w2.mp3'),
  'ko/work/w3': require('../../../assets/audio/trial/ko/work/w3.mp3'),
  'ko/media_culture/w2': require('../../../assets/audio/trial/ko/media_culture/w2.mp3'),
  'ko/housing_admin/w1': require('../../../assets/audio/trial/ko/housing_admin/w1.mp3'),
  'ko/housing_admin/w2': require('../../../assets/audio/trial/ko/housing_admin/w2.mp3'),
  'zh/travel/w1': require('../../../assets/audio/trial/zh/travel/w1.mp3'),
  'zh/travel/w2': require('../../../assets/audio/trial/zh/travel/w2.mp3'),
  'zh/family/w1': require('../../../assets/audio/trial/zh/family/w1.mp3'),
  'zh/work/w2': require('../../../assets/audio/trial/zh/work/w2.mp3'),
  'zh/work/w3': require('../../../assets/audio/trial/zh/work/w3.mp3'),
  'zh/work/sentence': require('../../../assets/audio/trial/zh/work/sentence.mp3'),
  'zh/media_culture/w1': require('../../../assets/audio/trial/zh/media_culture/w1.mp3'),
  'zh/media_culture/w2': require('../../../assets/audio/trial/zh/media_culture/w2.mp3'),
  'zh/media_culture/w3': require('../../../assets/audio/trial/zh/media_culture/w3.mp3'),
  'zh/media_culture/sentence': require('../../../assets/audio/trial/zh/media_culture/sentence.mp3'),
  'zh/housing_admin/w1': require('../../../assets/audio/trial/zh/housing_admin/w1.mp3'),
  'zh/housing_admin/w2': require('../../../assets/audio/trial/zh/housing_admin/w2.mp3'),
  'zh/housing_admin/w3': require('../../../assets/audio/trial/zh/housing_admin/w3.mp3'),
  'zh/housing_admin/sentence': require('../../../assets/audio/trial/zh/housing_admin/sentence.mp3'),
  'ru/travel/w1': require('../../../assets/audio/trial/ru/travel/w1.mp3'),
  'ru/travel/w2': require('../../../assets/audio/trial/ru/travel/w2.mp3'),
  'ru/travel/w3': require('../../../assets/audio/trial/ru/travel/w3.mp3'),
  'ru/travel/sentence': require('../../../assets/audio/trial/ru/travel/sentence.mp3'),
  'ru/family/w1': require('../../../assets/audio/trial/ru/family/w1.mp3'),
  'ru/family/w2': require('../../../assets/audio/trial/ru/family/w2.mp3'),
  'ru/family/w3': require('../../../assets/audio/trial/ru/family/w3.mp3'),
  'ru/family/sentence': require('../../../assets/audio/trial/ru/family/sentence.mp3'),
  'ru/work/w1': require('../../../assets/audio/trial/ru/work/w1.mp3'),
  'ru/work/w2': require('../../../assets/audio/trial/ru/work/w2.mp3'),
  'ru/work/w3': require('../../../assets/audio/trial/ru/work/w3.mp3'),
  'ru/work/sentence': require('../../../assets/audio/trial/ru/work/sentence.mp3'),
  'ru/media_culture/w1': require('../../../assets/audio/trial/ru/media_culture/w1.mp3'),
  'ru/media_culture/w2': require('../../../assets/audio/trial/ru/media_culture/w2.mp3'),
  'ru/media_culture/w3': require('../../../assets/audio/trial/ru/media_culture/w3.mp3'),
  'ru/media_culture/sentence': require('../../../assets/audio/trial/ru/media_culture/sentence.mp3'),
  'ru/housing_admin/w1': require('../../../assets/audio/trial/ru/housing_admin/w1.mp3'),
  'ru/housing_admin/w2': require('../../../assets/audio/trial/ru/housing_admin/w2.mp3'),
  'ru/housing_admin/w3': require('../../../assets/audio/trial/ru/housing_admin/w3.mp3'),
  'ru/housing_admin/sentence': require('../../../assets/audio/trial/ru/housing_admin/sentence.mp3'),
};

/**
 * Resolve a bundled trial clip to a URI expo-av can play, or null when the
 * clip has not been rendered.
 *
 * `localUri` is preferred: in a release build the asset has been copied into
 * the app container and that is a `file://` path, which plays without the
 * network. `uri` is the dev-server fallback.
 */
export function resolveTrialAudio(audioKey: string): string | null {
  const moduleId = TRIAL_AUDIO_MODULES[audioKey];
  if (moduleId === undefined) return null;

  try {
    const asset = Asset.fromModule(moduleId);
    return asset.localUri ?? asset.uri ?? null;
  } catch {
    // A clip that cannot be resolved is a missing clip: the pack falls back to
    // its text-only exercise rather than handing the runner a broken URI.
    return null;
  }
}

/** Every key the manifest currently has a clip for. Used by the tests. */
export function bundledTrialAudioKeys(): string[] {
  return Object.keys(TRIAL_AUDIO_MODULES);
}
