-- ============================================================================
-- Fluenci — French B2 "Complex Grammar" unit rebuild + fr grammar_rules seed
-- Unit: aabbccdd-2222-4006-0000-b20000000000 (French B2 course)
-- Replaces terminology-as-vocabulary template exercises with real grammar
-- practice. Progression per lesson (research.md §4.2, §7, §13.2):
--   recognition (multiple_choice) -> structured input (fill_blank / cloze)
--   -> production (word_form / transform / error_correction / construction /
--   translation).
-- All distractor options are >= 3 edits from the correct answer so the
-- fuzzy grader (lib/grading.ts, distance <= 2 tolerance) cannot accept them.
-- Staged file only — apply manually. DO NOT run automatically.
-- ============================================================================

BEGIN;

UPDATE units
SET description = 'B2 grammar: le subjonctif, les phrases avec si, le discours indirect, la voix passive et les pronoms relatifs'
WHERE id = 'aabbccdd-2222-4006-0000-b20000000000';

-- ────────────────────────────────────────────────────────────────────────────
-- Lesson 1 — Le subjonctif présent
-- ────────────────────────────────────────────────────────────────────────────
UPDATE lessons
SET title = 'Le subjonctif présent',
    description = 'The subjunctive after expressions of necessity, doubt, emotion and conjunctions like bien que'
WHERE id = 'aabbccdd-2222-4006-0001-b20000000000';

DELETE FROM exercises WHERE lesson_id = 'aabbccdd-2222-4006-0001-b20000000000';

INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, source_type) VALUES
('aabbccdd-2222-4006-0001-b20000000000', 'multiple_choice', 0,
 'Choose the correct form: Il faut que tu ___ tes devoirs avant ce soir.',
 'fasses', '{}', ARRAY['fasses','fais','feras','faire'],
 '« Il faut que » triggers a special mood.',
 'grammar', 'grammar', 'tap', 'subjonctif_present',
 ARRAY['fais','feras','faire'],
 '« Il faut que » expresses necessity and requires the subjunctive: fasses. « Fais » is indicative, « feras » is future, and the infinitive « faire » cannot follow « que » with its own subject.',
 'manual'),
('aabbccdd-2222-4006-0001-b20000000000', 'multiple_choice', 1,
 'Choose the correct form: Je doute qu''il ___ raison.',
 'ait', '{}', ARRAY['ait','a','aura','avoir'],
 '« Douter que » expresses doubt — which mood follows?',
 'grammar', 'grammar', 'tap', 'subjonctif_present',
 ARRAY['a','aura','avoir'],
 '« Douter que » expresses doubt, so the verb takes the subjunctive: ait. The indicative « a » and the future « aura » are used only after expressions of certainty, never after doubt.',
 'manual'),
('aabbccdd-2222-4006-0001-b20000000000', 'multiple_choice', 2,
 'Which sentence is correct?',
 'Bien qu''il soit fatigué, il continue à travailler.', '{}',
 ARRAY['Bien qu''il soit fatigué, il continue à travailler.','Bien qu''il est fatigué, il continue à travailler.','Bien qu''il sera fatigué, il continue à travailler.','Bien qu''il serait fatigué, il continue à travailler.'],
 '« Bien que » (although) is a subjunctive trigger.',
 'grammar', 'grammar', 'tap', 'subjonctif_present',
 ARRAY['Bien qu''il est fatigué, il continue à travailler.','Bien qu''il sera fatigué, il continue à travailler.','Bien qu''il serait fatigué, il continue à travailler.'],
 '« Bien que » always takes the subjunctive: soit. English speakers often use the indicative « est » because English ''although'' is followed by a normal verb form.',
 'manual'),
('aabbccdd-2222-4006-0001-b20000000000', 'fill_blank', 3,
 'Il est important que tu ___ à l''heure demain. (être)',
 'sois', '{}', NULL,
 'Subjunctive of « être », tu form.',
 'grammar', 'grammar', 'type', 'subjonctif_present',
 '{}',
 '« Il est important que » requires the subjunctive. « Être » is irregular: que tu sois. Keeping the indicative « es » is a very common error after impersonal expressions of importance.',
 'manual'),
('aabbccdd-2222-4006-0001-b20000000000', 'cloze_deletion', 4,
 'Je ne pense pas qu''elle ___ la vérité. (savoir)',
 'sache', '{}', NULL,
 '« Ne pas penser que » expresses doubt — which mood follows?',
 'grammar', 'grammar', 'type', 'subjonctif_present',
 '{}',
 'Negated opinion verbs like « ne pas penser que » take the subjunctive because the truth is in doubt. « Savoir » is irregular: sache. Affirmative « je pense que » would take the indicative « sait ».',
 'manual'),
('aabbccdd-2222-4006-0001-b20000000000', 'word_form', 5,
 'Complete with the correct form of « aller » : Il faut que j''___ à la banque avant midi.',
 'aille', '{}', NULL,
 'Irregular subjunctive stem of « aller ».',
 'grammar', 'grammar', 'type', 'subjonctif_present',
 '{}',
 'After « il faut que », « aller » takes its irregular subjunctive stem aill- : que j''aille. The indicative « vais » cannot follow an expression of necessity.',
 'manual'),
('aabbccdd-2222-4006-0001-b20000000000', 'error_correction', 6,
 'Il est essentiel que vous faites vos exercices chaque jour.',
 'Il est essentiel que vous fassiez vos exercices chaque jour.', '{}', NULL,
 'Check the mood after « il est essentiel que ».',
 'grammar', 'grammar', 'type', 'subjonctif_present',
 '{}',
 '« Il est essentiel que » demands the subjunctive: fassiez, not the indicative faites. Impersonal expressions of necessity or importance always trigger the subjunctive in the que-clause.',
 'manual'),
('aabbccdd-2222-4006-0001-b20000000000', 'sentence_transformation', 7,
 'Rewrite using « Il faut que » : Vous devez être patients.',
 'Il faut que vous soyez patients.',
 ARRAY['Il faut que vous soyez patient','Il faut que vous soyez patiente','Il faut que vous soyez patientes'], NULL,
 '« Il faut que » + subject + subjunctive.',
 'grammar', 'grammar', 'type', 'subjonctif_present',
 '{}',
 '« Devoir » + infinitive can be rephrased as « il faut que » + subjunctive. « Être » becomes soyez. Keeping the indicative « êtes » is the most frequent learner error in this pattern.',
 'manual'),
('aabbccdd-2222-4006-0001-b20000000000', 'sentence_construction', 8,
 'Arrange the words: Although it''s raining, we''re going out.',
 'Bien qu''il pleuve, nous sortons.', '{}', NULL,
 'Start with the concession (« Bien que… »).',
 'grammar', 'grammar', 'tap', 'subjonctif_present',
 '{}',
 '« Bien que » takes the subjunctive pleuve (from pleuvoir). The concession clause comes first, followed by a comma and the main clause « nous sortons ».',
 'manual'),
('aabbccdd-2222-4006-0001-b20000000000', 'translate_to_target', 9,
 'Translate: I want you to come with me.',
 'Je veux que tu viennes avec moi.',
 ARRAY['Je veux que vous veniez avec moi'], NULL,
 'French uses « vouloir que » + subjunctive — not an infinitive.',
 'grammar', 'grammar', 'type', 'subjonctif_present',
 '{}',
 'English ''want you to come'' becomes « vouloir que » + subjunctive: que tu viennes. French never says « je veux tu venir » — a change of subject after vouloir forces the subjunctive.',
 'manual');

-- ────────────────────────────────────────────────────────────────────────────
-- Lesson 2 — Les phrases avec « si »
-- ────────────────────────────────────────────────────────────────────────────
UPDATE lessons
SET title = 'Les phrases avec « si »',
    description = 'Hypothetical si-clauses: si + imparfait with the conditionnel présent, si + plus-que-parfait with the conditionnel passé'
WHERE id = 'aabbccdd-2222-4006-0002-b20000000000';

DELETE FROM exercises WHERE lesson_id = 'aabbccdd-2222-4006-0002-b20000000000';

INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, source_type) VALUES
('aabbccdd-2222-4006-0002-b20000000000', 'multiple_choice', 0,
 'Choose the correct form: Si tu ___ à ma place, tu accepterais cette offre.',
 'étais', '{}', ARRAY['étais','serais','es','seras'],
 'The si-clause takes the imparfait, never the conditional.',
 'grammar', 'grammar', 'tap', 'si_clauses_conditionnel',
 ARRAY['serais','es','seras'],
 'Unreal hypotheses use si + imparfait, with the conditional in the main clause. « Si tu serais » is the classic error — French never puts the conditional directly after hypothetical si.',
 'manual'),
('aabbccdd-2222-4006-0002-b20000000000', 'multiple_choice', 1,
 'Choose the correct form: Si elles avaient su, elles ___ pas venues.',
 'ne seraient', '{}', ARRAY['ne seraient','ne sont','ne seront','n''étaient'],
 'Past hypothesis → conditionnel passé (auxiliary + participle).',
 'grammar', 'grammar', 'tap', 'si_clauses_conditionnel',
 ARRAY['ne sont','ne seront','n''étaient'],
 'Si + plus-que-parfait pairs with the conditionnel passé: elles ne seraient pas venues. « Venir » uses être as its auxiliary, and the future « seront » is impossible in a past hypothesis.',
 'manual'),
('aabbccdd-2222-4006-0002-b20000000000', 'multiple_choice', 2,
 'Which sentence is correct?',
 'Si j''étais riche, je voyagerais davantage.', '{}',
 ARRAY['Si j''étais riche, je voyagerais davantage.','Si je serais riche, je voyagerais davantage.','Si je suis riche, je voyagerais davantage.','Si j''étais riche, j''avais voyagé davantage.'],
 'Imparfait after « si », conditional in the result clause.',
 'grammar', 'grammar', 'tap', 'si_clauses_conditionnel',
 ARRAY['Si je serais riche, je voyagerais davantage.','Si je suis riche, je voyagerais davantage.','Si j''étais riche, j''avais voyagé davantage.'],
 'An unreal present hypothesis takes si + imparfait (étais) with the conditionnel présent (voyagerais). The conditional never appears inside the si-clause, and mixing présent with a conditional result is inconsistent.',
 'manual'),
('aabbccdd-2222-4006-0002-b20000000000', 'fill_blank', 3,
 'Si nous ___ libres demain, nous irions à la plage. (être)',
 'étions', '{}', NULL,
 'Imparfait in the si-clause.',
 'grammar', 'grammar', 'type', 'si_clauses_conditionnel',
 '{}',
 'The main clause « nous irions » is conditional, so the si-clause needs the imparfait: étions. Using the present « sommes » or the conditional « serions » breaks the required tense pairing.',
 'manual'),
('aabbccdd-2222-4006-0002-b20000000000', 'cloze_deletion', 4,
 'Si elles avaient écouté, elles ___ compris la situation.',
 'auraient', '{}', NULL,
 'Conditionnel passé = conditional of avoir + past participle.',
 'grammar', 'grammar', 'type', 'si_clauses_conditionnel',
 '{}',
 'Si + plus-que-parfait (avaient écouté) calls for the conditionnel passé: auraient compris. The future « auront » is impossible because the hypothesis is unreal and already in the past.',
 'manual'),
('aabbccdd-2222-4006-0002-b20000000000', 'word_form', 5,
 'Put « pouvoir » in the conditionnel présent: Tu ___ m''aider, s''il te plaît ?',
 'pourrais', '{}', NULL,
 'Conditional stem pourr- + imparfait ending.',
 'grammar', 'grammar', 'type', 'si_clauses_conditionnel',
 '{}',
 'Polite requests use the conditionnel présent: pourrais (stem pourr- + ending -ais). The present « peux » sounds abrupt, and the future « pourras » makes a prediction, not a polite request.',
 'manual'),
('aabbccdd-2222-4006-0002-b20000000000', 'error_correction', 6,
 'Si je serais toi, je refuserais cette offre.',
 'Si j''étais toi, je refuserais cette offre.', '{}', NULL,
 'Which tense is allowed after hypothetical « si »?',
 'grammar', 'grammar', 'type', 'si_clauses_conditionnel',
 '{}',
 'French never uses the conditional immediately after hypothetical « si ». The si-clause takes the imparfait (étais); the conditional (refuserais) belongs only in the result clause.',
 'manual'),
('aabbccdd-2222-4006-0002-b20000000000', 'sentence_transformation', 7,
 'Put this hypothesis fully into the past: Si j''ai le temps, je viendrai.',
 'Si j''avais eu le temps, je serais venu.',
 ARRAY['Si j''avais eu le temps, je serais venue'], NULL,
 'Plus-que-parfait in the si-clause, conditionnel passé in the result.',
 'grammar', 'grammar', 'type', 'si_clauses_conditionnel',
 '{}',
 'A past unreal hypothesis uses si + plus-que-parfait (avais eu) with the conditionnel passé (serais venu). « Venir » takes être, so the participle agrees with the speaker.',
 'manual'),
('aabbccdd-2222-4006-0002-b20000000000', 'sentence_construction', 8,
 'Arrange the words: If I won the lottery, I would travel around the world.',
 'Si je gagnais au loto, je ferais le tour du monde.', '{}', NULL,
 'Si + imparfait, then the conditional.',
 'grammar', 'grammar', 'tap', 'si_clauses_conditionnel',
 '{}',
 '« Si je gagnais » (imparfait) sets up the unreal condition; « je ferais » (conditionnel présent) gives the imagined result. English ''won'' is past in form, which maps onto the French imparfait, and ''travel around the world'' is idiomatically « faire le tour du monde ».',
 'manual'),
('aabbccdd-2222-4006-0002-b20000000000', 'translate_to_target', 9,
 'Translate: If you had called me, I would have helped you.',
 'Si tu m''avais appelé, je t''aurais aidé.',
 ARRAY['Si tu m''avais appelée, je t''aurais aidée','Si tu m''avais appelé, je t''aurais aidée','Si tu m''avais appelée, je t''aurais aidé','Si vous m''aviez appelé, je vous aurais aidé','Si vous m''aviez appelée, je vous aurais aidée','Si tu m''avais téléphoné, je t''aurais aidé','Si tu m''avais téléphoné, je t''aurais aidée','Si vous m''aviez téléphoné, je vous aurais aidé'], NULL,
 'Third conditional: plus-que-parfait + conditionnel passé.',
 'grammar', 'grammar', 'type', 'si_clauses_conditionnel',
 '{}',
 '''Had called'' becomes the plus-que-parfait « avais appelé »; ''would have helped'' becomes the conditionnel passé « aurais aidé ». The participles may agree with the preceding object pronouns (m'', t'').',
 'manual');

-- ────────────────────────────────────────────────────────────────────────────
-- Lesson 3 — Le discours indirect
-- ────────────────────────────────────────────────────────────────────────────
UPDATE lessons
SET title = 'Le discours indirect',
    description = 'Reported speech: tense backshift (concordance des temps), pronoun shifts, si for yes/no questions and time expressions'
WHERE id = 'aabbccdd-2222-4006-0003-b20000000000';

DELETE FROM exercises WHERE lesson_id = 'aabbccdd-2222-4006-0003-b20000000000';

INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, source_type) VALUES
('aabbccdd-2222-4006-0003-b20000000000', 'multiple_choice', 0,
 'Elle a dit : « Je suis fatiguée. » → Elle a dit qu''elle ___ fatiguée.',
 'était', '{}', ARRAY['était','est','sera','serait'],
 'Backshift: présent → imparfait after a past reporting verb.',
 'grammar', 'grammar', 'tap', 'discours_indirect',
 ARRAY['est','sera','serait'],
 'After a past reporting verb (« a dit »), the present backshifts to the imparfait: était. Keeping « est » copies English, where backshift is optional; in French it is obligatory.',
 'manual'),
('aabbccdd-2222-4006-0003-b20000000000', 'multiple_choice', 1,
 'Il a demandé : « Est-ce que tu viendras demain ? » → Il a demandé ___ je viendrais le lendemain.',
 'si', '{}', ARRAY['si','que','quand','est-ce que'],
 'How are yes/no questions reported?',
 'grammar', 'grammar', 'tap', 'discours_indirect',
 ARRAY['que','quand','est-ce que'],
 'Reported yes/no questions are introduced by « si » (whether). « Que » reports statements, « quand » reports time questions, and « est-ce que » disappears entirely in indirect speech.',
 'manual'),
('aabbccdd-2222-4006-0003-b20000000000', 'multiple_choice', 2,
 'Which is the correct reported form? Ils ont annoncé : « Nous avons fini le projet. »',
 'Ils ont annoncé qu''ils avaient fini le projet.', '{}',
 ARRAY['Ils ont annoncé qu''ils avaient fini le projet.','Ils ont annoncé qu''ils ont fini le projet.','Ils ont annoncé qu''ils finissaient le projet.','Ils ont annoncé qu''ils vont finir le projet.'],
 'Passé composé → plus-que-parfait; nous → ils.',
 'grammar', 'grammar', 'tap', 'discours_indirect',
 ARRAY['Ils ont annoncé qu''ils ont fini le projet.','Ils ont annoncé qu''ils finissaient le projet.','Ils ont annoncé qu''ils vont finir le projet.'],
 'The passé composé backshifts to the plus-que-parfait in reported speech: avaient fini. The pronoun also shifts from nous to ils because the reporter is no longer the original speaker.',
 'manual'),
('aabbccdd-2222-4006-0003-b20000000000', 'fill_blank', 3,
 'Les voisins ont dit : « Nous irons au marché demain. » → Ils ont dit qu''ils ___ au marché le lendemain.',
 'iraient', '{}', NULL,
 'Futur simple → conditionnel présent.',
 'grammar', 'grammar', 'type', 'discours_indirect',
 '{}',
 'In reported speech after a past verb, the future « irons » becomes the conditional « iraient ». Note the time shift too: « demain » becomes « le lendemain ».',
 'manual'),
('aabbccdd-2222-4006-0003-b20000000000', 'cloze_deletion', 4,
 'Il m''a demandé : « Où as-tu acheté ce livre ? » → Il m''a demandé où j''___ acheté ce livre.',
 'avais', '{}', NULL,
 'Passé composé → plus-que-parfait.',
 'grammar', 'grammar', 'type', 'discours_indirect',
 '{}',
 'The passé composé « as acheté » backshifts to the plus-que-parfait « avais acheté ». The subject also changes from tu to je because the reported listener is now speaking about themselves.',
 'manual'),
('aabbccdd-2222-4006-0003-b20000000000', 'sentence_transformation', 5,
 'Put into reported speech: Paul a dit : « Je peux t''aider. »',
 'Paul a dit qu''il pouvait m''aider.', '{}', NULL,
 'Shift the pronouns and backshift the present tense.',
 'grammar', 'grammar', 'type', 'discours_indirect',
 '{}',
 '« Je » becomes « il », « te » becomes « me », and the present « peux » backshifts to the imparfait « pouvait ». Every deictic element must shift to the reporter''s point of view.',
 'manual'),
('aabbccdd-2222-4006-0003-b20000000000', 'error_correction', 6,
 'Elle a dit qu''elle est malade.',
 'Elle a dit qu''elle était malade.', '{}', NULL,
 'The reporting verb is in the past — check the tense that follows.',
 'grammar', 'grammar', 'type', 'discours_indirect',
 '{}',
 'After « elle a dit », the present must backshift to the imparfait: était. This concordance des temps is obligatory in French, unlike English where ''she said she is sick'' can pass in speech.',
 'manual'),
('aabbccdd-2222-4006-0003-b20000000000', 'word_form', 7,
 'Il a expliqué : « Je veux changer de travail. » → Put « vouloir » in the reported form: Il a expliqué qu''il ___ changer de travail.',
 'voulait', '{}', NULL,
 'Présent → imparfait.',
 'grammar', 'grammar', 'type', 'discours_indirect',
 '{}',
 'The present « veux » backshifts to the imparfait: voulait. The conditional « voudrait » would wrongly turn his firm statement into a softened wish.',
 'manual'),
('aabbccdd-2222-4006-0003-b20000000000', 'sentence_construction', 8,
 'Arrange the words: She asked me if I had seen her keys.',
 'Elle m''a demandé si j''avais vu ses clés.', '{}', NULL,
 '« si » + plus-que-parfait.',
 'grammar', 'grammar', 'tap', 'discours_indirect',
 '{}',
 'A reported yes/no question uses « si », and ''had seen'' is the plus-que-parfait « avais vu ». ''Her keys'' becomes « ses clés » — the possessive agrees with the noun, not the owner.',
 'manual'),
('aabbccdd-2222-4006-0003-b20000000000', 'translate_to_target', 9,
 'Translate: He said he would arrive late.',
 'Il a dit qu''il arriverait en retard.',
 ARRAY['Il a dit qu''il arriverait tard'], NULL,
 '''Would'' here is the conditional of reported speech.',
 'grammar', 'grammar', 'type', 'discours_indirect',
 '{}',
 '''Would arrive'' is not a hypothesis here but reported future: « arrivera » backshifts to the conditionnel « arriverait ». « Que » is obligatory in French even where English drops ''that''.',
 'manual');

-- ────────────────────────────────────────────────────────────────────────────
-- Lesson 4 — La voix passive et « on »
-- ────────────────────────────────────────────────────────────────────────────
UPDATE lessons
SET title = 'La voix passive et « on »',
    description = 'Passive voice with être + past participle, agent phrases with par, and the idiomatic on-construction'
WHERE id = 'aabbccdd-2222-4006-0004-b20000000000';

DELETE FROM exercises WHERE lesson_id = 'aabbccdd-2222-4006-0004-b20000000000';

INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, source_type) VALUES
('aabbccdd-2222-4006-0004-b20000000000', 'multiple_choice', 0,
 'Choose the correct form: La décision ___ par le directeur hier.',
 'a été prise', '{}', ARRAY['a été prise','a pris','est prise','a prise'],
 'Passive = être + past participle, agreeing with the subject.',
 'grammar', 'grammar', 'tap', 'voix_passive',
 ARRAY['a pris','est prise','a prise'],
 'The passive combines être with a past participle that agrees with the subject: la décision → prise. « A pris » is active and would absurdly mean the decision did the taking; « est prise » is the wrong tense for « hier ».',
 'manual'),
('aabbccdd-2222-4006-0004-b20000000000', 'multiple_choice', 1,
 'Choose the correct preposition: Ce roman a été écrit ___ cette auteure célèbre.',
 'par', '{}', ARRAY['par','de','avec','chez'],
 'Action verbs take this preposition before the agent.',
 'grammar', 'grammar', 'tap', 'voix_passive',
 ARRAY['de','avec','chez'],
 'The agent of a passive action verb is introduced by « par ». « De » appears only with verbs of state or emotion (aimé de tous), and « avec » marks instruments, not agents.',
 'manual'),
('aabbccdd-2222-4006-0004-b20000000000', 'multiple_choice', 2,
 'Which sentence means the same as: On a volé mon vélo ?',
 'Mon vélo a été volé.', '{}',
 ARRAY['Mon vélo a été volé.','Mon vélo a volé.','Quelqu''un a été volé mon vélo.','Mon vélo s''est volé.'],
 '« On » + active verb ≈ passive with an unknown agent.',
 'grammar', 'grammar', 'tap', 'voix_passive',
 ARRAY['Mon vélo a volé.','Quelqu''un a été volé mon vélo.','Mon vélo s''est volé.'],
 '« On a volé mon vélo » and « Mon vélo a été volé » both leave the agent unknown. « Mon vélo a volé » means the bike flew, and « s''est volé » wrongly makes the bike steal itself.',
 'manual'),
('aabbccdd-2222-4006-0004-b20000000000', 'fill_blank', 3,
 'Le nouveau pont ___ inauguré par la maire la semaine prochaine.',
 'sera', ARRAY['va être','va etre'], NULL,
 'Future passive: future of être + participle.',
 'grammar', 'grammar', 'type', 'voix_passive',
 '{}',
 'In the passive, tense is carried entirely by « être »: sera inauguré is the future passive (« va être inauguré » also works). « La semaine prochaine » rules out any past or present form.',
 'manual'),
('aabbccdd-2222-4006-0004-b20000000000', 'cloze_deletion', 4,
 'Ce tableau a ___ peint par Monet en 1873.',
 'été', ARRAY['ete'], NULL,
 'Passé composé passive: a + ? + participle.',
 'grammar', 'grammar', 'type', 'voix_passive',
 '{}',
 'The passé composé passive stacks two participles: a été peint — the participle of être (été) plus the participle of the main verb. Learners often drop « été », accidentally producing an active sentence.',
 'manual'),
('aabbccdd-2222-4006-0004-b20000000000', 'word_form', 5,
 'Put « construire » in the past participle: Le stade a été ___ en deux ans.',
 'construit', '{}', NULL,
 'Irregular participle ending in -uit.',
 'grammar', 'grammar', 'type', 'voix_passive',
 '{}',
 '« Construire » has the irregular past participle construit. The subject « le stade » is masculine singular, so no extra agreement ending is added.',
 'manual'),
('aabbccdd-2222-4006-0004-b20000000000', 'error_correction', 6,
 'Le voleur a arrêté par la police hier soir.',
 'Le voleur a été arrêté par la police hier soir.', ARRAY['Le voleur a ete arrete par la police hier soir'], NULL,
 'Something is missing between the auxiliary and the participle.',
 'grammar', 'grammar', 'type', 'voix_passive',
 '{}',
 'The passive requires être: a été arrêté. Without « été » the sentence is active and absurdly means the thief arrested someone. « Par la police » signals that a passive was intended.',
 'manual'),
('aabbccdd-2222-4006-0004-b20000000000', 'sentence_transformation', 7,
 'Put into the passive voice: Une entreprise japonaise construira le nouveau musée.',
 'Le nouveau musée sera construit par une entreprise japonaise.', '{}', NULL,
 'Object → subject; keep the future tense on « être ».',
 'grammar', 'grammar', 'type', 'voix_passive',
 '{}',
 'The object « le nouveau musée » becomes the subject, « construira » becomes sera construit (future of être + participle), and the old subject follows « par » as the agent.',
 'manual'),
('aabbccdd-2222-4006-0004-b20000000000', 'sentence_construction', 8,
 'Arrange the words: French is spoken in more than twenty countries.',
 'Le français est parlé dans plus de vingt pays.', '{}', NULL,
 'Present passive: est + participle.',
 'grammar', 'grammar', 'tap', 'voix_passive',
 '{}',
 'General facts use the present passive: est parlé. The participle stays masculine singular to agree with « le français ». No agent is expressed because it is people in general.',
 'manual'),
('aabbccdd-2222-4006-0004-b20000000000', 'translate_to_target', 9,
 'Translate using « on »: Someone stole my wallet.',
 'On a volé mon portefeuille.',
 ARRAY['On m''a volé mon portefeuille'], NULL,
 'French prefers « on » where English says ''someone'' or uses the passive.',
 'grammar', 'grammar', 'type', 'voix_passive',
 '{}',
 'French avoids heavy passives for unknown agents: « on » + active verb is the idiomatic equivalent. « On a volé mon portefeuille » corresponds to both ''someone stole'' and ''my wallet was stolen''.',
 'manual');

-- ────────────────────────────────────────────────────────────────────────────
-- Lesson 5 — Les pronoms relatifs
-- ────────────────────────────────────────────────────────────────────────────
UPDATE lessons
SET title = 'Les pronoms relatifs',
    description = 'Advanced relative pronouns: dont, lequel/laquelle after prepositions, auquel, où, and ce que / ce dont'
WHERE id = 'aabbccdd-2222-4006-0005-b20000000000';

DELETE FROM exercises WHERE lesson_id = 'aabbccdd-2222-4006-0005-b20000000000';

INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, source_type) VALUES
('aabbccdd-2222-4006-0005-b20000000000', 'multiple_choice', 0,
 'Choose the correct pronoun: C''est le livre ___ je t''ai parlé.',
 'dont', '{}', ARRAY['dont','que','qui','lequel'],
 '« Parler de » — the pronoun must absorb « de ».',
 'grammar', 'grammar', 'tap', 'pronoms_relatifs',
 ARRAY['que','qui','lequel'],
 '« Parler de quelque chose » requires dont, which replaces de + noun. « Que » only replaces a direct object and « qui » a subject — neither carries the needed « de ».',
 'manual'),
('aabbccdd-2222-4006-0005-b20000000000', 'multiple_choice', 1,
 'Choose the correct pronoun: La réunion pendant ___ il a dormi a duré trois heures.',
 'laquelle', '{}', ARRAY['laquelle','lequel','dont','que'],
 'After a preposition, use a form of « lequel » agreeing with the noun.',
 'grammar', 'grammar', 'tap', 'pronoms_relatifs',
 ARRAY['lequel','dont','que'],
 'After prepositions like « pendant », French uses lequel-forms agreeing in gender: la réunion → laquelle. « Dont » already contains « de » and can never follow another preposition.',
 'manual'),
('aabbccdd-2222-4006-0005-b20000000000', 'multiple_choice', 2,
 'Choose the correct pronoun: Je ne comprends pas ___ tu veux dire.',
 'ce que', '{}', ARRAY['ce que','ce dont','quoi','que'],
 '''What'' as the object of the verb = ce + ?',
 'grammar', 'grammar', 'tap', 'pronoms_relatifs',
 ARRAY['ce dont','quoi','que'],
 'English ''what'' heading a clause is « ce que » when it is the direct object of the verb (dire quelque chose). Bare « que » or « quoi » cannot introduce this kind of clause.',
 'manual'),
('aabbccdd-2222-4006-0005-b20000000000', 'fill_blank', 3,
 'L''entreprise pour ___ elle travaille est basée à Lyon.',
 'laquelle', '{}', NULL,
 'Preposition + lequel-form; « entreprise » is feminine.',
 'grammar', 'grammar', 'type', 'pronoms_relatifs',
 '{}',
 '« Pour » demands a lequel-form, and « entreprise » is feminine singular: pour laquelle. « Pour qui » is reserved for people, and bare « lequel » would be masculine.',
 'manual'),
('aabbccdd-2222-4006-0005-b20000000000', 'cloze_deletion', 4,
 'Voici les documents ___ vous aurez besoin pour votre inscription.',
 'dont', '{}', NULL,
 '« Avoir besoin de » — which pronoun contains « de »?',
 'grammar', 'grammar', 'type', 'pronoms_relatifs',
 '{}',
 '« Avoir besoin de » makes dont obligatory: les documents dont vous aurez besoin. « Que » is the classic error because English ''that you need'' shows no trace of « de ».',
 'manual'),
('aabbccdd-2222-4006-0005-b20000000000', 'cloze_deletion', 5,
 'Le quartier ___ j''ai grandi a beaucoup changé.',
 'où', '{}', NULL,
 'The relative pronoun for place (and time).',
 'grammar', 'grammar', 'type', 'pronoms_relatifs',
 '{}',
 '« Où » is the relative pronoun for place: le quartier où j''ai grandi. English speakers often write « que » here because ''the neighborhood that I grew up in'' uses ''that''.',
 'manual'),
('aabbccdd-2222-4006-0005-b20000000000', 'error_correction', 6,
 'C''est un problème à qui personne n''a pensé.',
 'C''est un problème auquel personne n''a pensé.', '{}', NULL,
 '« À qui » is only for people.',
 'grammar', 'grammar', 'type', 'pronoms_relatifs',
 '{}',
 '« Penser à » + thing requires auquel (à + lequel). « À qui » can only refer to people; « un problème » is a thing, so the contracted form auquel is obligatory.',
 'manual'),
('aabbccdd-2222-4006-0005-b20000000000', 'sentence_transformation', 7,
 'Combine the two sentences with « dont »: Je te parlais d''un film. Ce film passe au cinéma.',
 'Le film dont je te parlais passe au cinéma.', '{}', NULL,
 '« Dont » replaces « de + noun » right after its antecedent.',
 'grammar', 'grammar', 'type', 'pronoms_relatifs',
 '{}',
 '« Dont » absorbs the « de » of « parler de »: le film dont je te parlais. The relative clause sits directly after its antecedent, before the main verb « passe ».',
 'manual'),
('aabbccdd-2222-4006-0005-b20000000000', 'sentence_construction', 8,
 'Arrange the words: The people with whom I work are very friendly.',
 'Les gens avec qui je travaille sont très sympathiques.', '{}', NULL,
 'Preposition + « qui » for people.',
 'grammar', 'grammar', 'tap', 'pronoms_relatifs',
 '{}',
 'For people after a preposition, French uses avec qui (avec lesquels is also possible). The relative clause « avec qui je travaille » interrupts subject and verb, mirroring the English structure.',
 'manual'),
('aabbccdd-2222-4006-0005-b20000000000', 'translate_to_target', 9,
 'Translate: That''s exactly what I need.',
 'C''est exactement ce dont j''ai besoin.',
 ARRAY['C''est exactement ce qu''il me faut'], NULL,
 '« Avoir besoin de » → ce dont.',
 'grammar', 'grammar', 'type', 'pronoms_relatifs',
 '{}',
 '''What I need'' with « avoir besoin de » becomes ce dont j''ai besoin — the « de » survives inside « dont ». « Ce que j''ai besoin » is the most common learner error at this level.',
 'manual');

-- ────────────────────────────────────────────────────────────────────────────
-- Lesson 6 — Review & Test (mixes all five topics)
-- ────────────────────────────────────────────────────────────────────────────
UPDATE lessons
SET title = 'Review & Test',
    description = 'Mixed practice: subjonctif, si-clauses, discours indirect, voix passive and pronoms relatifs'
WHERE id = 'aabbccdd-2222-4006-0006-b20000000000';

DELETE FROM exercises WHERE lesson_id = 'aabbccdd-2222-4006-0006-b20000000000';

INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, source_type) VALUES
('aabbccdd-2222-4006-0006-b20000000000', 'multiple_choice', 0,
 'Choose the correct form: Nous attendrons jusqu''à ce qu''il ___ moins froid.',
 'fasse', '{}', ARRAY['fasse','fait','fera','faisait'],
 '« Jusqu''à ce que » + subjunctive.',
 'grammar', 'grammar', 'tap', 'subjonctif_present',
 ARRAY['fait','fera','faisait'],
 '« Jusqu''à ce que » always takes the subjunctive: fasse. The future « fera » feels logical to English speakers (''until it will be''), but French grammar requires the subjunctive here.',
 'manual'),
('aabbccdd-2222-4006-0006-b20000000000', 'multiple_choice', 1,
 'Ils ont dit : « Nous avons gagné. » → Ils ont dit qu''ils ___ gagné.',
 'avaient', '{}', ARRAY['avaient','ont','auront','avez'],
 'Passé composé → plus-que-parfait.',
 'grammar', 'grammar', 'tap', 'discours_indirect',
 ARRAY['ont','auront','avez'],
 'In reported speech after a past verb, the passé composé backshifts to the plus-que-parfait: avaient gagné. The pronoun shifts from nous to ils as the point of view changes.',
 'manual'),
('aabbccdd-2222-4006-0006-b20000000000', 'cloze_deletion', 2,
 'Si tu m''avais prévenu, je ne ___ pas venu.',
 'serais', '{}', NULL,
 'Conditionnel passé with être.',
 'grammar', 'grammar', 'type', 'si_clauses_conditionnel',
 '{}',
 'A past unreal condition (si + plus-que-parfait) takes the conditionnel passé: je ne serais pas venu. « Venir » conjugates with être, so serais — not aurais — is the correct auxiliary.',
 'manual'),
('aabbccdd-2222-4006-0006-b20000000000', 'fill_blank', 3,
 'Ce château ___ construit au XVIe siècle.',
 'a été', ARRAY['fut','a ete'], NULL,
 'Past passive: passé composé of être + participle.',
 'grammar', 'grammar', 'type', 'voix_passive',
 '{}',
 'The completed past passive needs a été: ce château a été construit. The literary passé simple « fut » is also correct in writing. « Est construit » would describe a present state, not the historical event.',
 'manual'),
('aabbccdd-2222-4006-0006-b20000000000', 'fill_blank', 4,
 'La façon ___ il me parle me dérange.',
 'dont', '{}', NULL,
 '« La façon… » takes the pronoun that contains « de ».',
 'grammar', 'grammar', 'type', 'pronoms_relatifs',
 '{}',
 'French says la façon dont (the way in which): dont is fixed after « la façon ». English ''the way that he talks'' pushes learners toward « que », which is ungrammatical here.',
 'manual'),
('aabbccdd-2222-4006-0006-b20000000000', 'error_correction', 5,
 'Je ne crois pas qu''il peut résoudre ce problème seul.',
 'Je ne crois pas qu''il puisse résoudre ce problème seul.', '{}', NULL,
 'Negated belief — check the mood.',
 'grammar', 'grammar', 'type', 'subjonctif_present',
 '{}',
 '« Ne pas croire que » expresses doubt and takes the subjunctive: puisse. The indicative « peut » is only correct in the affirmative « je crois qu''il peut ».',
 'manual'),
('aabbccdd-2222-4006-0006-b20000000000', 'sentence_transformation', 6,
 'Put into the active voice: Ce roman a été traduit par une équipe de spécialistes.',
 'Une équipe de spécialistes a traduit ce roman.', '{}', NULL,
 'The agent after « par » becomes the subject.',
 'grammar', 'grammar', 'type', 'voix_passive',
 '{}',
 'Reversing the passive, the agent « une équipe de spécialistes » becomes the subject and « a été traduit » becomes the simple passé composé a traduit. The participle no longer agrees because « ce roman » now follows the verb.',
 'manual'),
('aabbccdd-2222-4006-0006-b20000000000', 'sentence_transformation', 7,
 'Put into reported speech: Elle m''a demandé : « As-tu fini ton travail ? »',
 'Elle m''a demandé si j''avais fini mon travail.', '{}', NULL,
 'Yes/no question → « si »; shift the tense and the possessive.',
 'grammar', 'grammar', 'type', 'discours_indirect',
 '{}',
 'The yes/no question is reported with « si »; « as fini » backshifts to the plus-que-parfait « avais fini »; and « ton travail » becomes « mon travail » from the answerer''s point of view.',
 'manual'),
('aabbccdd-2222-4006-0006-b20000000000', 'sentence_construction', 8,
 'Arrange the words: If we had left earlier, we would not have missed the train.',
 'Si nous étions partis plus tôt, nous n''aurions pas raté le train.', '{}', NULL,
 'Plus-que-parfait (être) + conditionnel passé (avoir).',
 'grammar', 'grammar', 'tap', 'si_clauses_conditionnel',
 '{}',
 '« Partir » takes être in the plus-que-parfait (étions partis), while « rater » takes avoir in the conditionnel passé (n''aurions pas raté). Note how ne…pas wraps only the auxiliary.',
 'manual'),
('aabbccdd-2222-4006-0006-b20000000000', 'translate_to_target', 9,
 'Translate: It''s a shame that you can''t stay longer.',
 'C''est dommage que tu ne puisses pas rester plus longtemps.',
 ARRAY['C''est dommage que vous ne puissiez pas rester plus longtemps','Il est dommage que tu ne puisses pas rester plus longtemps','Il est dommage que vous ne puissiez pas rester plus longtemps'], NULL,
 '« C''est dommage que » + subjunctive.',
 'grammar', 'grammar', 'type', 'subjonctif_present',
 '{}',
 'Emotion and judgement expressions like « c''est dommage que » take the subjunctive: puisses. ''Longer'' after a verb of duration is « plus longtemps », never « plus long ».',
 'manual');

-- ────────────────────────────────────────────────────────────────────────────
-- Grammar rules reference set — French (language = 'fr')
-- 5 rules per CEFR level (A1, A2, B1, B2). B2 rule_names deliberately match
-- the target_grammar tags used above so RuleCard lookups resolve exactly.
-- examples shape: [{"target": ..., "native": ...}] (see RuleCard parseExamples)
-- ────────────────────────────────────────────────────────────────────────────

INSERT INTO grammar_rules (language, cefr_level, rule_name, title, explanation, examples, common_errors, tags) VALUES
-- ── A1 ──
('fr', 'A1', 'articles_definis_indefinis', 'Definite & Indefinite Articles',
 'French nouns almost always need an article. Use le / la / les for specific or general things (le café = coffee in general) and un / une / des for unspecified ones. Le and la shorten to l'' before a vowel sound.',
 '[{"target": "J''aime le fromage.", "native": "I like cheese."}, {"target": "Elle achète des pommes.", "native": "She is buying (some) apples."}]'::jsonb,
 '[{"error": "J''aime fromage.", "correction": "J''aime le fromage.", "note": "Unlike English, French keeps the article before general nouns."}, {"error": "le école", "correction": "l''école", "note": "Le and la contract to l'' before a vowel sound."}]'::jsonb,
 ARRAY['articles','nouns','a1']),
('fr', 'A1', 'genre_des_noms', 'Noun Gender',
 'Every French noun is masculine or feminine, and its article and adjectives must match. Endings give clues: -tion, -té and -ure are usually feminine; -age, -eau and -isme usually masculine. Always learn a noun together with its article.',
 '[{"target": "une décision importante", "native": "an important decision"}, {"target": "un voyage intéressant", "native": "an interesting trip"}]'::jsonb,
 '[{"error": "la problème", "correction": "le problème", "note": "Nouns in -ème of Greek origin are masculine."}, {"error": "un maison", "correction": "une maison", "note": "Maison is feminine; the article must agree."}]'::jsonb,
 ARRAY['gender','nouns','a1']),
('fr', 'A1', 'present_verbes_er', 'Present Tense of -er Verbs',
 'Regular -er verbs drop -er and add: -e, -es, -e, -ons, -ez, -ent. Je parle, tu parles, il parle, nous parlons, vous parlez, ils parlent. Four of the six forms sound identical — spelling matters more than sound.',
 '[{"target": "Nous parlons français.", "native": "We speak French."}, {"target": "Ils habitent à Paris.", "native": "They live in Paris."}]'::jsonb,
 '[{"error": "ils parle", "correction": "ils parlent", "note": "The -ent ending is silent but required in writing."}, {"error": "je parles", "correction": "je parle", "note": "Only the tu form takes -es."}]'::jsonb,
 ARRAY['present','conjugation','a1']),
('fr', 'A1', 'negation_ne_pas', 'Negation with ne… pas',
 'French negation has two parts that wrap around the conjugated verb: ne + verb + pas. Ne becomes n'' before a vowel. After a negation, un / une / des usually become de: je n''ai pas de voiture.',
 '[{"target": "Je ne comprends pas.", "native": "I don''t understand."}, {"target": "Elle n''a pas de frères.", "native": "She doesn''t have any brothers."}]'::jsonb,
 '[{"error": "Je pas comprends.", "correction": "Je ne comprends pas.", "note": "Both ne and pas are needed, around the verb."}, {"error": "Je n''ai pas une voiture.", "correction": "Je n''ai pas de voiture.", "note": "Indefinite articles become de after a negation."}]'::jsonb,
 ARRAY['negation','a1']),
('fr', 'A1', 'accord_adjectifs', 'Adjective Agreement & Position',
 'Adjectives agree in gender and number with their noun: add -e for feminine, -s for plural (grand, grande, grands, grandes). Most adjectives follow the noun; a few short common ones (beau, bon, petit, grand…) come before it.',
 '[{"target": "une voiture verte", "native": "a green car"}, {"target": "de petites rues calmes", "native": "small quiet streets"}]'::jsonb,
 '[{"error": "une robe vert", "correction": "une robe verte", "note": "Feminine nouns need the feminine adjective form."}, {"error": "une rouge voiture", "correction": "une voiture rouge", "note": "Color adjectives follow the noun in French."}]'::jsonb,
 ARRAY['adjectives','agreement','a1']),

-- ── A2 ──
('fr', 'A2', 'passe_compose', 'Le passé composé',
 'The passé composé describes completed past actions: present of avoir or être + past participle. Most verbs take avoir; movement and reflexive verbs take être, and their participle agrees with the subject: elle est arrivée.',
 '[{"target": "J''ai fini mes devoirs.", "native": "I finished my homework."}, {"target": "Elle est arrivée hier soir.", "native": "She arrived last night."}]'::jsonb,
 '[{"error": "J''ai allé au cinéma.", "correction": "Je suis allé au cinéma.", "note": "Aller takes être, not avoir."}, {"error": "Elle est arrivé.", "correction": "Elle est arrivée.", "note": "With être, the participle agrees with the subject."}]'::jsonb,
 ARRAY['past','passe-compose','a2']),
('fr', 'A2', 'imparfait', 'L''imparfait',
 'The imparfait describes past habits, background and ongoing states: take the nous form of the present, drop -ons, and add -ais, -ais, -ait, -ions, -iez, -aient. Use it for what was happening, not for one-time completed events.',
 '[{"target": "Quand j''étais petit, je jouais au foot.", "native": "When I was little, I used to play football."}, {"target": "Il pleuvait et les rues étaient vides.", "native": "It was raining and the streets were empty."}]'::jsonb,
 '[{"error": "Hier, je jouais au foot pendant une heure.", "correction": "Hier, j''ai joué au foot pendant une heure.", "note": "A completed, bounded event takes the passé composé."}, {"error": "je étais", "correction": "j''étais", "note": "Je elides to j'' before a vowel."}]'::jsonb,
 ARRAY['past','imparfait','a2']),
('fr', 'A2', 'futur_proche', 'Le futur proche (aller + infinitive)',
 'For plans and near-future events, use the present of aller + infinitive: je vais partir (I''m going to leave). It is the everyday spoken future. In the negative, ne… pas wraps around aller: je ne vais pas partir.',
 '[{"target": "Nous allons visiter le musée demain.", "native": "We are going to visit the museum tomorrow."}, {"target": "Tu vas adorer ce film.", "native": "You are going to love this movie."}]'::jsonb,
 '[{"error": "Je vais partir pas.", "correction": "Je ne vais pas partir.", "note": "The negation wraps around the conjugated verb aller."}, {"error": "Nous allons visitons le musée.", "correction": "Nous allons visiter le musée.", "note": "After aller, the second verb stays in the infinitive."}]'::jsonb,
 ARRAY['future','futur-proche','a2']),
('fr', 'A2', 'comparatif_superlatif', 'Comparatives & Superlatives',
 'Compare with plus / moins / aussi + adjective + que: plus rapide que (faster than). The superlative adds the article: le plus rapide. Bon is irregular: meilleur (better), le meilleur (the best) — never « plus bon ».',
 '[{"target": "Ce café est meilleur que l''autre.", "native": "This coffee is better than the other one."}, {"target": "C''est la ville la plus belle de France.", "native": "It''s the most beautiful city in France."}]'::jsonb,
 '[{"error": "plus bon", "correction": "meilleur", "note": "Bon has an irregular comparative, like English good/better."}, {"error": "la plus belle ville dans le monde", "correction": "la plus belle ville du monde", "note": "After a superlative, ''in'' is de, not dans."}]'::jsonb,
 ARRAY['comparison','adjectives','a2']),
('fr', 'A2', 'imperatif', 'L''impératif',
 'Commands drop the subject pronoun: Parle ! Parlons ! Parlez ! For -er verbs, the tu form loses its -s: mange ! Object pronouns follow an affirmative command with a hyphen (donne-moi) but precede a negative one (ne me donne pas).',
 '[{"target": "Écoutez bien la question.", "native": "Listen carefully to the question."}, {"target": "Donne-moi ton adresse.", "native": "Give me your address."}]'::jsonb,
 '[{"error": "Manges ta soupe !", "correction": "Mange ta soupe !", "note": "-er verbs drop the -s in the tu imperative."}, {"error": "Me donne le livre.", "correction": "Donne-moi le livre.", "note": "Pronouns follow affirmative commands, joined by a hyphen."}]'::jsonb,
 ARRAY['imperative','commands','a2']),

-- ── B1 ──
('fr', 'B1', 'futur_simple', 'Le futur simple',
 'The futur simple attaches -ai, -as, -a, -ons, -ez, -ont to the infinitive (parlerai) or an irregular stem (ser-, aur-, ir-, fer-, viendr-). Use it for predictions and promises. After quand referring to the future, French also uses the future: quand tu arriveras.',
 '[{"target": "Je t''appellerai demain.", "native": "I will call you tomorrow."}, {"target": "Quand tu arriveras, on mangera.", "native": "When you arrive, we will eat."}]'::jsonb,
 '[{"error": "Quand tu arrives demain, on mangera.", "correction": "Quand tu arriveras demain, on mangera.", "note": "Unlike English, French uses the future after quand for future events."}, {"error": "je serai aller", "correction": "j''irai", "note": "Aller has the irregular future stem ir-."}]'::jsonb,
 ARRAY['future','futur-simple','b1']),
('fr', 'B1', 'pronoms_cod_coi', 'Direct & Indirect Object Pronouns',
 'Object pronouns come before the conjugated verb: le / la / les replace direct objects, lui / leur replace à + person. Je le vois (I see him); je lui parle (I talk to him). With the passé composé they precede the auxiliary: je l''ai vu.',
 '[{"target": "Je lui ai téléphoné hier.", "native": "I phoned him/her yesterday."}, {"target": "Ces livres ? Je les ai déjà lus.", "native": "Those books? I''ve already read them."}]'::jsonb,
 '[{"error": "Je vois le.", "correction": "Je le vois.", "note": "Object pronouns go before the verb, not after."}, {"error": "Je le parle.", "correction": "Je lui parle.", "note": "Parler à requires the indirect pronoun lui."}]'::jsonb,
 ARRAY['pronouns','objects','b1']),
('fr', 'B1', 'pronoms_y_en', 'The Pronouns y and en',
 'Y replaces à + place or thing (j''y vais = I''m going there); en replaces de + thing or a quantity (j''en veux deux = I want two of them). Both come before the verb. En is obligatory with numbers and quantities — English leaves it out.',
 '[{"target": "Tu vas à Lyon ? — Oui, j''y vais lundi.", "native": "Are you going to Lyon? — Yes, I''m going (there) on Monday."}, {"target": "Des pommes ? J''en ai acheté trois.", "native": "Apples? I bought three (of them)."}]'::jsonb,
 '[{"error": "J''ai acheté trois.", "correction": "J''en ai acheté trois.", "note": "With a number and no noun, en is obligatory in French."}, {"error": "Je vais y.", "correction": "J''y vais.", "note": "Y precedes the conjugated verb."}]'::jsonb,
 ARRAY['pronouns','y','en','b1']),
('fr', 'B1', 'conditionnel_present', 'Le conditionnel présent',
 'The conditional combines the future stem with imparfait endings: je voudrais, tu pourrais. Use it for polite requests (je voudrais un café), advice with devoir (tu devrais dormir), and imagined results of hypotheses (j''achèterais une maison).',
 '[{"target": "Je voudrais un billet pour Nice, s''il vous plaît.", "native": "I would like a ticket to Nice, please."}, {"target": "Tu devrais parler au professeur.", "native": "You should talk to the teacher."}]'::jsonb,
 '[{"error": "Je veux un café. (to a waiter)", "correction": "Je voudrais un café.", "note": "The conditional softens requests; the present can sound blunt."}, {"error": "tu devrais de dormir", "correction": "tu devrais dormir", "note": "Devoir connects directly to the infinitive, without de."}]'::jsonb,
 ARRAY['conditional','politeness','b1']),
('fr', 'B1', 'pronoms_relatifs_simples', 'Relative Pronouns qui, que, où',
 'Qui replaces the subject of the relative clause (la femme qui parle); que replaces the direct object (le livre que je lis); où replaces a place or time (la ville où je vis). Choose by function in the clause, not by whether the noun is a person.',
 '[{"target": "C''est l''ami qui m''a aidé.", "native": "He''s the friend who helped me."}, {"target": "Le film que nous avons vu était excellent.", "native": "The film that we saw was excellent."}]'::jsonb,
 '[{"error": "le livre qui je lis", "correction": "le livre que je lis", "note": "The clause already has a subject (je), so the pronoun must be que."}, {"error": "la ville que je vis", "correction": "la ville où je vis", "note": "For places, French uses où, even where English uses ''that''."}]'::jsonb,
 ARRAY['relative-pronouns','b1']),

-- ── B2 ──
('fr', 'B2', 'subjonctif_present', 'Le subjonctif présent',
 'Use the subjunctive after expressions of necessity, will, emotion, doubt (il faut que, vouloir que, douter que) and conjunctions like bien que, pour que, jusqu''à ce que. Key irregular stems: fasse, sois, aie, aille, puisse, sache, vienne.',
 '[{"target": "Il faut que tu fasses tes devoirs.", "native": "You have to do your homework."}, {"target": "Bien qu''il soit tard, elle travaille encore.", "native": "Although it is late, she is still working."}]'::jsonb,
 '[{"error": "Il faut que tu fais tes devoirs.", "correction": "Il faut que tu fasses tes devoirs.", "note": "Il faut que triggers the subjunctive, not the indicative."}, {"error": "Je veux que tu venir.", "correction": "Je veux que tu viennes.", "note": "English ''want you to come'' becomes vouloir que + subjunctive, never an infinitive."}]'::jsonb,
 ARRAY['subjunctive','mood','b2']),
('fr', 'B2', 'si_clauses_conditionnel', 'Hypothetical si-Clauses',
 'Three patterns: si + présent → futur (real); si + imparfait → conditionnel présent (unreal present); si + plus-que-parfait → conditionnel passé (unreal past). The conditional and the future never appear inside the si-clause itself.',
 '[{"target": "Si j''étais riche, je voyagerais davantage.", "native": "If I were rich, I would travel more."}, {"target": "Si tu m''avais appelé, je t''aurais aidé.", "native": "If you had called me, I would have helped you."}]'::jsonb,
 '[{"error": "Si je serais riche…", "correction": "Si j''étais riche…", "note": "Never the conditional after hypothetical si — use the imparfait."}, {"error": "Si j''avais su, je venais.", "correction": "Si j''avais su, je serais venu.", "note": "A past hypothesis needs the conditionnel passé in the result clause."}]'::jsonb,
 ARRAY['conditional','si-clauses','hypothesis','b2']),
('fr', 'B2', 'discours_indirect', 'Le discours indirect',
 'After a past reporting verb, tenses backshift: présent → imparfait, passé composé → plus-que-parfait, futur → conditionnel. Yes/no questions are reported with si; pronouns, possessives and time words shift too (demain → le lendemain).',
 '[{"target": "Elle a dit qu''elle était fatiguée.", "native": "She said (that) she was tired."}, {"target": "Il a demandé si je viendrais le lendemain.", "native": "He asked if I would come the next day."}]'::jsonb,
 '[{"error": "Elle a dit qu''elle est fatiguée.", "correction": "Elle a dit qu''elle était fatiguée.", "note": "The backshift is obligatory in French, unlike casual English."}, {"error": "Il a demandé est-ce que je viendrais.", "correction": "Il a demandé si je viendrais.", "note": "Est-ce que disappears in reported questions; use si."}]'::jsonb,
 ARRAY['reported-speech','tense-agreement','b2']),
('fr', 'B2', 'voix_passive', 'The Passive Voice & on',
 'The passive uses être + past participle, which agrees with the subject: la décision a été prise. Tense is carried by être. The agent follows par (or de with state/emotion verbs). For unknown agents, French prefers on + active verb: on a volé mon vélo.',
 '[{"target": "Ce roman a été écrit par une auteure célèbre.", "native": "This novel was written by a famous author."}, {"target": "On a volé mon portefeuille.", "native": "My wallet was stolen. / Someone stole my wallet."}]'::jsonb,
 '[{"error": "Le voleur a arrêté par la police.", "correction": "Le voleur a été arrêté par la police.", "note": "Dropping été destroys the passive and reverses the meaning."}, {"error": "La lettre a été écrit.", "correction": "La lettre a été écrite.", "note": "The participle agrees with the passive subject."}]'::jsonb,
 ARRAY['passive','on-construction','b2']),
('fr', 'B2', 'pronoms_relatifs', 'Advanced Relative Pronouns (dont, lequel, ce qui/ce que)',
 'Dont replaces de + noun (le livre dont je parle). After other prepositions use lequel-forms agreeing in gender (la réunion pendant laquelle…; à + lequel → auquel). Without an antecedent, use ce qui (subject), ce que (object) or ce dont (with de).',
 '[{"target": "Voici les documents dont vous aurez besoin.", "native": "Here are the documents (that) you will need."}, {"target": "C''est exactement ce dont j''ai besoin.", "native": "That''s exactly what I need."}]'::jsonb,
 '[{"error": "le film que je te parlais", "correction": "le film dont je te parlais", "note": "Parler de requires dont, which absorbs the de."}, {"error": "un problème à qui personne n''a pensé", "correction": "un problème auquel personne n''a pensé", "note": "À qui is only for people; things need auquel."}]'::jsonb,
 ARRAY['relative-pronouns','dont','lequel','b2'])
ON CONFLICT (language, rule_name) DO UPDATE SET
  cefr_level = EXCLUDED.cefr_level,
  title = EXCLUDED.title,
  explanation = EXCLUDED.explanation,
  examples = EXCLUDED.examples,
  common_errors = EXCLUDED.common_errors,
  tags = EXCLUDED.tags;

COMMIT;
