-- ═══════════════════════════════════════════════════════════════
-- Italian B2 "Complex Grammar" unit rebuild + grammar_rules seed
-- Unit: aabbccdd-4444-4006-0000-b20000000000 (course: it B2)
-- Replaces terminology-as-vocabulary junk with real grammar practice.
-- Progression per lesson (research.md §4.2, §7): recognition (MC) →
-- structured input (fill/cloze) → production (word_form, transform,
-- error_correction, construction, translation). Every exercise has a
-- ≤60-word metalinguistic explanation (§7.2 rule cards, §10 feedback).
-- STAGED ONLY — do not apply without review.
-- ═══════════════════════════════════════════════════════════════

BEGIN;

UPDATE units
SET description = 'The essential B2 structures: the subjunctive, hypotheticals, the passive and si passivante, reported speech, and combined pronouns — practised in real sentences.'
WHERE id = 'aabbccdd-4444-4006-0000-b20000000000';

-- ─── Lesson 1: Il Congiuntivo — Present & Past Subjunctive ─────

UPDATE lessons
SET title = 'Il Congiuntivo: Present & Past Subjunctive',
    description = 'Use the subjunctive after verbs of opinion, emotion and doubt: penso che, è importante che, benché.'
WHERE id = 'aabbccdd-4444-4006-0001-b20000000000';

DELETE FROM exercises WHERE lesson_id = 'aabbccdd-4444-4006-0001-b20000000000';

INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, source_type) VALUES
('aabbccdd-4444-4006-0001-b20000000000', 'multiple_choice', 0,
 'Choose the correct form: Penso che Luca ___ ragione.',
 'abbia', '{}', ARRAY['abbia','ha','aveva','ha avuto'],
 'Penso che triggers the subjunctive mood.',
 'grammar', 'grammar', 'tap', 'congiuntivo_presente',
 ARRAY['ha','aveva','ha avuto'],
 'After opinion verbs like penso che, Italian requires the subjunctive: abbia, the present subjunctive of avere. The indicative forms ha, aveva and ha avuto are the classic English-speaker error here.',
 'seed'),
('aabbccdd-4444-4006-0001-b20000000000', 'multiple_choice', 1,
 'Choose the correct form: È importante che voi ___ attenzione.',
 'facciate', '{}', ARRAY['facciate','fate','farete','avete fatto'],
 'Impersonal expressions like è importante che take the subjunctive.',
 'grammar', 'grammar', 'tap', 'congiuntivo_presente',
 ARRAY['fate','farete','avete fatto'],
 'Impersonal expressions of necessity (è importante che, bisogna che) require the subjunctive: facciate, present subjunctive of fare. The indicative fate and the future farete are ungrammatical in this clause.',
 'seed'),
('aabbccdd-4444-4006-0001-b20000000000', 'fill_blank', 2,
 'Credo che loro ___ stranieri. (essere)',
 'siano', '{}', NULL,
 'Present subjunctive of essere, 3rd person plural.',
 'grammar', 'grammar', 'type', 'congiuntivo_presente',
 '{}',
 'Credo che expresses belief, so the verb takes the subjunctive: siano, the present subjunctive of essere. The indicative sono would be wrong after credere che.',
 'seed'),
('aabbccdd-4444-4006-0001-b20000000000', 'fill_blank', 3,
 'Dubito che Maria ___ la verità ieri. (dire)',
 'abbia detto', '{}', NULL,
 'Congiuntivo passato = present subjunctive of avere/essere + past participle.',
 'grammar', 'grammar', 'type', 'congiuntivo_passato',
 '{}',
 'To express doubt about a completed action, use the congiuntivo passato: abbia detto (subjunctive of avere + participle). Dubito che never takes the indicative ha detto.',
 'seed'),
('aabbccdd-4444-4006-0001-b20000000000', 'cloze_deletion', 4,
 'Benché ___ stanco, Marco continua a lavorare.',
 'sia', '{}', NULL,
 'Benché (although) always takes the subjunctive.',
 'grammar', 'grammar', 'type', 'congiuntivo_presente',
 '{}',
 'Concessive conjunctions like benché, sebbene and nonostante always require the subjunctive: sia. With a present-tense main clause, use the present subjunctive, never the indicative è.',
 'seed'),
('aabbccdd-4444-4006-0001-b20000000000', 'word_form', 5,
 'Non credo che tu ___ (capire) il problema.',
 'capisca', '{}', NULL,
 'Capire is an -isc- verb; singular subjunctive forms all end in -isca.',
 'grammar', 'grammar', 'type', 'congiuntivo_presente',
 '{}',
 'Capire inserts -isc-: the present subjunctive is capisca for all singular persons. Non credo che demands the subjunctive; the indicative capisci would be wrong.',
 'seed'),
('aabbccdd-4444-4006-0001-b20000000000', 'sentence_transformation', 6,
 'Rewrite starting with ''Penso che'': Laura è molto intelligente.',
 'Penso che Laura sia molto intelligente', ARRAY['Penso che Laura sia molto intelligente.'], NULL,
 'The indicative è must change mood after penso che.',
 'grammar', 'grammar', 'type', 'congiuntivo_presente',
 '{}',
 'Embedding a fact under penso che shifts the verb from indicative to subjunctive: è becomes sia. Everything else in the sentence stays the same.',
 'seed'),
('aabbccdd-4444-4006-0001-b20000000000', 'error_correction', 7,
 'Penso che Luca è molto simpatico.',
 'Penso che Luca sia molto simpatico', ARRAY['Penso che Luca sia molto simpatico.'], NULL,
 'Check the mood of the verb after penso che.',
 'grammar', 'grammar', 'type', 'congiuntivo_presente',
 '{}',
 'The indicative è cannot follow penso che: opinion verbs require the subjunctive sia. Using the indicative after verbs of opinion is the most frequent B2 subjunctive error.',
 'seed'),
('aabbccdd-4444-4006-0001-b20000000000', 'sentence_construction', 8,
 'Build the Italian sentence: ''It is possible that the train is late.''',
 'È possibile che il treno sia in ritardo', '{}', NULL,
 'Start with the impersonal expression; it triggers the subjunctive.',
 'grammar', 'grammar', 'tap', 'congiuntivo_presente',
 '{}',
 'È possibile che expresses possibility, so the embedded verb is subjunctive: sia in ritardo. Word order mirrors English: impersonal expression + che + subject + verb.',
 'seed'),
('aabbccdd-4444-4006-0001-b20000000000', 'translate_to_target', 9,
 'Translate to Italian: I think Marco is right.',
 'Penso che Marco abbia ragione', ARRAY['Credo che Marco abbia ragione','Io penso che Marco abbia ragione','Io credo che Marco abbia ragione','Penso che Marco abbia ragione.'], NULL,
 'To be right = avere ragione; remember the mood after penso che.',
 'grammar', 'grammar', 'type', 'congiuntivo_presente',
 '{}',
 'Penso che (or credo che) requires the subjunctive: abbia ragione, not ha ragione. Italian uses avere ragione (to have reason) where English uses to be right.',
 'seed');

-- ─── Lesson 2: Hypotheticals — Se + Imperfect Subjunctive ──────

UPDATE lessons
SET title = 'Hypotheticals: Se + Imperfect Subjunctive',
    description = 'Build unreal conditions: se avessi..., farei... — the imperfect subjunctive paired with the conditional.'
WHERE id = 'aabbccdd-4444-4006-0002-b20000000000';

DELETE FROM exercises WHERE lesson_id = 'aabbccdd-4444-4006-0002-b20000000000';

INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, source_type) VALUES
('aabbccdd-4444-4006-0002-b20000000000', 'multiple_choice', 0,
 'Choose the correct form: Se ___ ricco, comprerei una casa al mare.',
 'fossi', '{}', ARRAY['fossi','sono','sarei','ero'],
 'Unreal conditions use se + imperfect subjunctive.',
 'grammar', 'grammar', 'tap', 'periodo_ipotetico',
 ARRAY['sono','sarei','ero'],
 'An unreal present condition uses se + imperfect subjunctive (fossi) with the conditional in the main clause (comprerei). Se sarei is the classic error: the conditional never follows se.',
 'seed'),
('aabbccdd-4444-4006-0002-b20000000000', 'multiple_choice', 1,
 'Choose the correct form: Se avessi tempo, ti ___ più spesso.',
 'aiuterei', '{}', ARRAY['aiuterei','aiuto','aiutavo','aiutassi'],
 'The main clause of an unreal condition takes the conditional.',
 'grammar', 'grammar', 'tap', 'periodo_ipotetico',
 ARRAY['aiuto','aiutavo','aiutassi'],
 'The result clause of a type-2 hypothesis takes the present conditional: aiuterei. The subjunctive (aiutassi) belongs only in the se-clause, and the indicative aiuto/aiutavo breaks the pattern.',
 'seed'),
('aabbccdd-4444-4006-0002-b20000000000', 'fill_blank', 2,
 'Se io ___ più tempo libero, imparerei il pianoforte. (avere)',
 'avessi', '{}', NULL,
 'Imperfect subjunctive of avere, 1st person singular.',
 'grammar', 'grammar', 'type', 'congiuntivo_imperfetto',
 '{}',
 'The se-clause of an unreal condition takes the imperfect subjunctive: avessi. The main clause imparerei (conditional) signals that the situation is imagined, not real.',
 'seed'),
('aabbccdd-4444-4006-0002-b20000000000', 'cloze_deletion', 3,
 'Se Marco studiasse di più, ___ l''esame senza problemi.',
 'supererebbe', ARRAY['passerebbe'], NULL,
 'Present conditional of superare (to pass).',
 'grammar', 'grammar', 'type', 'periodo_ipotetico',
 '{}',
 'After a se-clause with the imperfect subjunctive (studiasse), the main clause needs the present conditional: supererebbe. Superare un esame is the standard collocation for passing an exam.',
 'seed'),
('aabbccdd-4444-4006-0002-b20000000000', 'word_form', 4,
 'Mangeremmo fuori più spesso se i ristoranti ___ (costare) meno.',
 'costassero', '{}', NULL,
 'Imperfect subjunctive, 3rd person plural.',
 'grammar', 'grammar', 'type', 'congiuntivo_imperfetto',
 '{}',
 'In the se-clause of an unreal hypothesis, use the imperfect subjunctive: costassero (3rd plural). The conditional mangeremmo in the main clause confirms the unreal reading.',
 'seed'),
('aabbccdd-4444-4006-0002-b20000000000', 'fill_blank', 5,
 'Volevo che tu mi ___ la verità. (dire)',
 'dicessi', '{}', NULL,
 'A past main verb shifts the subjunctive to the imperfect.',
 'grammar', 'grammar', 'type', 'congiuntivo_imperfetto',
 '{}',
 'After a past-tense verb of will (volevo che), the subordinate clause takes the imperfect subjunctive: dicessi. Tense agreement (concordanza dei tempi) rules out the present subjunctive dica.',
 'seed'),
('aabbccdd-4444-4006-0002-b20000000000', 'sentence_transformation', 6,
 'Rewrite as one ''se'' sentence (unreal condition): Non ho soldi, quindi non viaggio.',
 'Se avessi soldi, viaggerei', ARRAY['Se avessi soldi viaggerei','Se io avessi soldi, viaggerei','Se avessi i soldi, viaggerei','Se avessi dei soldi, viaggerei'], NULL,
 'Turn the real situation into its unreal opposite: se + imperfect subjunctive, then conditional.',
 'grammar', 'grammar', 'type', 'periodo_ipotetico',
 '{}',
 'The real facts (no money, no travel) become an unreal condition: se avessi soldi (imperfect subjunctive) + viaggerei (conditional). Both verbs must change; keeping the indicative is ungrammatical.',
 'seed'),
('aabbccdd-4444-4006-0002-b20000000000', 'error_correction', 7,
 'Se sarei in te, accetterei quel lavoro.',
 'Se fossi in te, accetterei quel lavoro', ARRAY['Se fossi in te accetterei quel lavoro','Se io fossi in te, accetterei quel lavoro','Se fossi in te, accetterei quel lavoro.'], NULL,
 'One of the two verbs is in the wrong mood after se.',
 'grammar', 'grammar', 'type', 'periodo_ipotetico',
 '{}',
 'The conditional never follows se: se sarei must become se fossi (imperfect subjunctive). The conditional accetterei is correct in the main clause. Se sarei is a stigmatized error even for natives.',
 'seed'),
('aabbccdd-4444-4006-0002-b20000000000', 'sentence_construction', 8,
 'Build the Italian sentence: ''If I were you, I would not say anything.''',
 'Se fossi in te non direi niente', ARRAY['Non direi niente se fossi in te'], NULL,
 'Se + imperfect subjunctive first, conditional in the result clause.',
 'grammar', 'grammar', 'tap', 'periodo_ipotetico',
 '{}',
 'Se fossi in te (if I were you) uses the imperfect subjunctive; non direi niente uses the conditional. Italian allows the double negative non... niente — it is required, not optional.',
 'seed'),
('aabbccdd-4444-4006-0002-b20000000000', 'translate_to_target', 9,
 'Translate to Italian: If it were sunny, we would go to the beach.',
 'Se ci fosse il sole, andremmo in spiaggia', ARRAY['Se ci fosse il sole andremmo in spiaggia','Se ci fosse il sole, andremmo al mare','Se ci fosse il sole andremmo al mare'], NULL,
 'There is sun = c''è il sole; go to the beach = andare in spiaggia / al mare.',
 'grammar', 'grammar', 'type', 'periodo_ipotetico',
 '{}',
 'Unreal weather condition: se ci fosse il sole (imperfect subjunctive of esserci) + andremmo (conditional). Both in spiaggia and al mare translate to the beach.',
 'seed');

-- ─── Lesson 3: The Passive & Si Passivante ─────────────────────

UPDATE lessons
SET title = 'The Passive & Si Passivante',
    description = 'Form passives with essere/venire + past participle, and use the impersonal si passivante of written Italian.'
WHERE id = 'aabbccdd-4444-4006-0003-b20000000000';

DELETE FROM exercises WHERE lesson_id = 'aabbccdd-4444-4006-0003-b20000000000';

INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, source_type) VALUES
('aabbccdd-4444-4006-0003-b20000000000', 'multiple_choice', 0,
 'Choose the passive form: Il progetto ___ dal nostro team.',
 'è gestito', '{}', ARRAY['è gestito','gestisce','si gestisce','sta gestendo'],
 'Passive = essere + past participle; the agent takes da.',
 'grammar', 'grammar', 'tap', 'passivo',
 ARRAY['gestisce','si gestisce','sta gestendo'],
 'The passive is essere + past participle: è gestito, with the agent introduced by da. Active gestisce would need the team as subject, and si gestisce cannot combine with a da-agent.',
 'seed'),
('aabbccdd-4444-4006-0003-b20000000000', 'multiple_choice', 1,
 'Choose the correct form: Queste scarpe ___ in Italia l''anno scorso.',
 'sono state prodotte', '{}', ARRAY['sono state prodotte','hanno prodotto','sono prodotte','producevano'],
 'A finished past event needs the compound passive.',
 'grammar', 'grammar', 'tap', 'passivo',
 ARRAY['hanno prodotto','sono prodotte','producevano'],
 'Past passive: sono state prodotte — essere + stato + participle, both agreeing with the feminine plural scarpe. Sono prodotte is present passive and clashes with l''anno scorso.',
 'seed'),
('aabbccdd-4444-4006-0003-b20000000000', 'fill_blank', 2,
 'Il nuovo museo ___ inaugurato dal sindaco domani. (futuro)',
 'sarà', ARRAY['verrà'], NULL,
 'Future passive: future of essere (or venire) + participle.',
 'grammar', 'grammar', 'type', 'passivo',
 '{}',
 'Future passive: sarà inaugurato. In simple tenses venire can replace essere with an action reading: verrà inaugurato is equally correct. The agent takes da: dal sindaco.',
 'seed'),
('aabbccdd-4444-4006-0003-b20000000000', 'fill_blank', 3,
 'La decisione è stata ___ dal direttore. (prendere)',
 'presa', '{}', NULL,
 'The participle agrees with the subject: la decisione is feminine singular.',
 'grammar', 'grammar', 'type', 'passivo',
 '{}',
 'In passives with essere, the past participle agrees with the subject: la decisione (feminine singular) takes presa, the irregular participle of prendere. Preso would break agreement.',
 'seed'),
('aabbccdd-4444-4006-0003-b20000000000', 'cloze_deletion', 4,
 'In quel negozio si ___ prodotti biologici. (vendere)',
 'vendono', '{}', NULL,
 'With si passivante, the verb agrees with the plural noun.',
 'grammar', 'grammar', 'type', 'si_passivante',
 '{}',
 'With the si passivante, the verb agrees with its grammatical subject: prodotti biologici is plural, so si vendono. Singular si vende would need a singular noun like frutta.',
 'seed'),
('aabbccdd-4444-4006-0003-b20000000000', 'word_form', 5,
 'Il ladro ___ (arrestare) dalla polizia ieri sera.',
 'è stato arrestato', '{}', NULL,
 'Compound past passive: essere in the passato prossimo + participle.',
 'grammar', 'grammar', 'type', 'passivo',
 '{}',
 'Past passive of arrestare in the passato prossimo: è stato arrestato. With a recent time expression like ieri sera, avoid the passato remoto (fu/venne arrestato), which is reserved for the distant, narrative past.',
 'seed'),
('aabbccdd-4444-4006-0003-b20000000000', 'sentence_transformation', 6,
 'Rewrite in the passive voice: Il governo approverà la nuova legge.',
 'La nuova legge sarà approvata dal governo', ARRAY['La nuova legge verrà approvata dal governo','La nuova legge sarà approvata dal governo.'], NULL,
 'The object becomes the subject; the agent takes da.',
 'grammar', 'grammar', 'type', 'passivo',
 '{}',
 'The object la nuova legge becomes the subject; approverà becomes sarà (or verrà) approvata, agreeing with legge; the old subject takes da: dal governo.',
 'seed'),
('aabbccdd-4444-4006-0003-b20000000000', 'error_correction', 7,
 'Questo vino si producono in Toscana.',
 'Questo vino si produce in Toscana', ARRAY['Questo vino si produce in Toscana.'], NULL,
 'Check the agreement between the verb and the noun.',
 'grammar', 'grammar', 'type', 'si_passivante',
 '{}',
 'The si passivante agrees with the noun: questo vino is singular, so si produce. Si producono would require a plural subject like questi vini.',
 'seed'),
('aabbccdd-4444-4006-0003-b20000000000', 'sentence_construction', 8,
 'Build the Italian sentence: ''The house was sold last month.''',
 'La casa è stata venduta il mese scorso', ARRAY['Il mese scorso la casa è stata venduta'], NULL,
 'Compound passive: essere + stata + participle, all feminine singular.',
 'grammar', 'grammar', 'tap', 'passivo',
 '{}',
 'Past passive with essere: è stata venduta. Both stata and venduta agree with la casa (feminine singular). Last month = il mese scorso, no preposition needed.',
 'seed'),
('aabbccdd-4444-4006-0003-b20000000000', 'translate_to_target', 9,
 'Translate to Italian: In Italy a lot of coffee is drunk.',
 'In Italia si beve molto caffè', ARRAY['In Italia si beve tanto caffè','Si beve molto caffè in Italia','Si beve tanto caffè in Italia'], NULL,
 'Use the si passivante — Italian avoids the full passive here.',
 'grammar', 'grammar', 'type', 'si_passivante',
 '{}',
 'General statements use the si passivante: si beve molto caffè. The verb is singular because caffè is singular. The full passive (molto caffè è bevuto) is grammatical but unnatural.',
 'seed');

-- ─── Lesson 4: Reported Speech (Discorso Indiretto) ────────────

UPDATE lessons
SET title = 'Reported Speech (Discorso Indiretto)',
    description = 'Report statements and questions with tense backshift: present → imperfect, passato prossimo → trapassato, future → past conditional.'
WHERE id = 'aabbccdd-4444-4006-0004-b20000000000';

DELETE FROM exercises WHERE lesson_id = 'aabbccdd-4444-4006-0004-b20000000000';

INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, source_type) VALUES
('aabbccdd-4444-4006-0004-b20000000000', 'multiple_choice', 0,
 'Marco ha detto: ''Sono stanco.'' → Marco ha detto che ___ stanco.',
 'era', '{}', ARRAY['era','è stato','sarà','fosse'],
 'Reporting after a past verb backshifts the present tense.',
 'grammar', 'grammar', 'tap', 'discorso_indiretto',
 ARRAY['è stato','sarà','fosse'],
 'After a past reporting verb, a present tense backshifts to the imperfect: sono → era. The subjunctive fosse is wrong here: dire che introduces reported statements in the indicative.',
 'seed'),
('aabbccdd-4444-4006-0004-b20000000000', 'multiple_choice', 1,
 'Laura ha detto: ''Ho perso le chiavi.'' → Laura ha detto che ___ le chiavi.',
 'aveva perso', '{}', ARRAY['aveva perso','perdeva','avrebbe perso','avrà perso'],
 'A completed past action moves one step further back.',
 'grammar', 'grammar', 'tap', 'discorso_indiretto',
 ARRAY['perdeva','avrebbe perso','avrà perso'],
 'A passato prossimo in direct speech backshifts to the trapassato prossimo: ho perso → aveva perso, because the loss happened before the past act of reporting. The imperfect perdeva would describe an ongoing action.',
 'seed'),
('aabbccdd-4444-4006-0004-b20000000000', 'fill_blank', 2,
 'Direct: ''Ti chiamerò domani.'' → Mi ha promesso che mi ___ il giorno dopo. (chiamare)',
 'avrebbe chiamato', ARRAY['avrebbe chiamata'], NULL,
 'Future in the past = condizionale passato.',
 'grammar', 'grammar', 'type', 'discorso_indiretto',
 '{}',
 'Italian reports a future after a past verb with the condizionale passato: chiamerò → avrebbe chiamato. English uses "would call", but Italian requires the compound conditional, never the simple one.',
 'seed'),
('aabbccdd-4444-4006-0004-b20000000000', 'fill_blank', 3,
 'Direct: ''Vengo qui ogni giorno.'' → Ha detto che andava ___ ogni giorno.',
 'lì', ARRAY['là'], NULL,
 'Place words shift away from the speaker in reported speech.',
 'grammar', 'grammar', 'type', 'discorso_indiretto',
 '{}',
 'In reported speech, deictics shift away from the original speaker: qui → lì/là, and venire → andare. The present vengo also backshifts to the imperfect andava.',
 'seed'),
('aabbccdd-4444-4006-0004-b20000000000', 'cloze_deletion', 4,
 'Il professore ha chiesto agli studenti se ___ capito la lezione.',
 'avessero', ARRAY['avevano'], NULL,
 'Reported question about a prior event: trapassato, subjunctive or indicative.',
 'grammar', 'grammar', 'type', 'discorso_indiretto',
 '{}',
 'After chiedere se, Italian allows the subjunctive (avessero capito, more formal) or the indicative (avevano capito). Either way the trapassato marks that the understanding came before the asking.',
 'seed'),
('aabbccdd-4444-4006-0004-b20000000000', 'word_form', 5,
 'Ha detto: ''Non posso venire.'' → Ha detto che non ___ (potere) venire.',
 'poteva', '{}', NULL,
 'Present indicative backshifts to the imperfect.',
 'grammar', 'grammar', 'type', 'discorso_indiretto',
 '{}',
 'The present posso backshifts to the imperfect poteva after the past reporting verb ha detto. Modal verbs follow the same backshift rules as any other verb.',
 'seed'),
('aabbccdd-4444-4006-0004-b20000000000', 'sentence_transformation', 6,
 'Rewrite in reported speech: Anna ha detto: ''Abito a Roma.''',
 'Anna ha detto che abitava a Roma', ARRAY['Ha detto che abitava a Roma','Anna ha detto di abitare a Roma','Ha detto di abitare a Roma','Anna ha detto che abitava a Roma.'], NULL,
 'Backshift the present tense; first person becomes third.',
 'grammar', 'grammar', 'type', 'discorso_indiretto',
 '{}',
 'Two changes: the person shifts (abito → third person) and the tense backshifts (present → imperfect): abitava. The connector che is obligatory in Italian reported speech.',
 'seed'),
('aabbccdd-4444-4006-0004-b20000000000', 'error_correction', 7,
 'Mi ha detto che verrà alla festa il giorno dopo.',
 'Mi ha detto che sarebbe venuto alla festa il giorno dopo', ARRAY['Mi ha detto che sarebbe venuta alla festa il giorno dopo','Mi ha detto che sarebbe venuto alla festa il giorno dopo.'], NULL,
 'Il giorno dopo shows this future was reported from the past.',
 'grammar', 'grammar', 'type', 'discorso_indiretto',
 '{}',
 'The shifted time phrase il giorno dopo proves the future is viewed from the past, so it must be condizionale passato: sarebbe venuto (or venuta), never the simple future verrà.',
 'seed'),
('aabbccdd-4444-4006-0004-b20000000000', 'sentence_construction', 8,
 'Build the Italian sentence: ''Luca said that he was hungry.''',
 'Luca ha detto che aveva fame', '{}', NULL,
 'To be hungry = avere fame; backshift it to the imperfect.',
 'grammar', 'grammar', 'tap', 'discorso_indiretto',
 '{}',
 'The direct speech ho fame backshifts to aveva fame after ha detto. Italian uses avere fame (to have hunger), so the auxiliary to backshift is avere, not essere.',
 'seed'),
('aabbccdd-4444-4006-0004-b20000000000', 'translate_to_target', 9,
 'Translate to Italian: She said that she would arrive late.',
 'Ha detto che sarebbe arrivata tardi', ARRAY['Lei ha detto che sarebbe arrivata tardi','Ha detto che sarebbe arrivata in ritardo','Lei ha detto che sarebbe arrivata in ritardo','Disse che sarebbe arrivata tardi'], NULL,
 'Would arrive = future in the past; arrivare takes essere.',
 'grammar', 'grammar', 'type', 'discorso_indiretto',
 '{}',
 'Future in the past = condizionale passato: sarebbe arrivata. Arrivare takes essere, so the participle agrees with the feminine subject: arrivata. Late = tardi or in ritardo.',
 'seed');

-- ─── Lesson 5: Combined Pronouns (Pronomi Combinati) ───────────

UPDATE lessons
SET title = 'Combined Pronouns (Pronomi Combinati)',
    description = 'Fuse indirect and direct pronouns — me lo, te la, glielo — with correct placement and participle agreement.'
WHERE id = 'aabbccdd-4444-4006-0005-b20000000000';

DELETE FROM exercises WHERE lesson_id = 'aabbccdd-4444-4006-0005-b20000000000';

INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, source_type) VALUES
('aabbccdd-4444-4006-0005-b20000000000', 'multiple_choice', 0,
 'In the sentence ''Te lo presto volentieri'', what does ''te lo'' mean?',
 'to you + it', '{}', ARRAY['to you + it','to me + it','to you + them','to him + it'],
 'The indirect pronoun comes first and changes its vowel.',
 'grammar', 'grammar', 'tap', 'pronomi_combinati',
 ARRAY['to me + it','to you + them','to him + it'],
 'Te lo combines the indirect ti (to you), which becomes te before another pronoun, with the direct lo (it, masculine singular): I will gladly lend it to you.',
 'seed'),
('aabbccdd-4444-4006-0005-b20000000000', 'multiple_choice', 1,
 'Choose the correct sentence for: ''I gave it to her.'' (it = il libro)',
 'Gliel''ho dato', '{}', ARRAY['Gliel''ho dato','Le lo ho dato','Gli ho dato','L''ho data a lui'],
 'Le + lo fuse into a single word before the verb.',
 'grammar', 'grammar', 'tap', 'pronomi_combinati',
 ARRAY['Le lo ho dato','Gli ho dato','L''ho data a lui'],
 'Le (to her) + lo (it) fuse into glielo, elided before ho: Gliel''ho dato. Both le and gli share the combined form glie-; keeping them separate (le lo) is never correct.',
 'seed'),
('aabbccdd-4444-4006-0005-b20000000000', 'fill_blank', 2,
 'Mi presti la penna? — Sì, ___ presto subito. (pronome combinato)',
 'te la', '{}', NULL,
 'Combine ''to you'' + ''it'' (la penna); ti changes to te.',
 'grammar', 'grammar', 'type', 'pronomi_combinati',
 '{}',
 'Ti becomes te before a direct pronoun, and la penna is replaced by la: te la presto. Combined pronouns stand together directly before the conjugated verb.',
 'seed'),
('aabbccdd-4444-4006-0005-b20000000000', 'fill_blank', 3,
 'Hai dato le chiavi a Marco? — Sì, ___ ho date. (pronome combinato)',
 'gliele', '{}', NULL,
 'Combine ''a Marco'' (gli) + ''le chiavi'' (le) into one word.',
 'grammar', 'grammar', 'type', 'pronomi_combinati',
 '{}',
 'A Marco → gli, le chiavi → le: they fuse as gliele, one word. The past participle then agrees with the preceding direct pronoun: date, feminine plural.',
 'seed'),
('aabbccdd-4444-4006-0005-b20000000000', 'cloze_deletion', 4,
 'Chi ti ha regalato questo orologio? — ___ ha regalato mia nonna.',
 'Me lo', ARRAY['me l'''], NULL,
 'Include yourself: mi + lo → ?',
 'grammar', 'grammar', 'type', 'pronomi_combinati',
 '{}',
 'Mi becomes me before lo: Me lo ha regalato (often elided to Me l''ha). The watch (orologio) is masculine singular, so the direct pronoun is lo.',
 'seed'),
('aabbccdd-4444-4006-0005-b20000000000', 'word_form', 5,
 'Hai comprato le mele? — Sì, le ho ___ (comprare) al mercato.',
 'comprate', '{}', NULL,
 'The participle agrees with the preceding direct pronoun le.',
 'grammar', 'grammar', 'type', 'pronomi_combinati',
 '{}',
 'With a preceding direct-object pronoun (le = le mele), the past participle must agree in gender and number: comprate. Without the pronoun there is no agreement: ho comprato le mele.',
 'seed'),
('aabbccdd-4444-4006-0005-b20000000000', 'sentence_transformation', 6,
 'Replace both objects with combined pronouns: Ho prestato la macchina a Luca.',
 'Gliel''ho prestata', ARRAY['Gliela ho prestata','Gliel''ho prestata.'], NULL,
 'a Luca → gli; la macchina → la; then fuse and elide.',
 'grammar', 'grammar', 'type', 'pronomi_combinati',
 '{}',
 'A Luca → gli, la macchina → la: gli + la = gliela, elided before ho: Gliel''ho. The participle agrees with the feminine la: prestata, not prestato.',
 'seed'),
('aabbccdd-4444-4006-0005-b20000000000', 'error_correction', 7,
 'Ho incontrato Maria e le l''ho detto subito.',
 'Ho incontrato Maria e gliel''ho detto subito', ARRAY['Ho incontrato Maria e glielo ho detto subito','Ho incontrato Maria e gliel''ho detto subito.'], NULL,
 'Le cannot stand next to lo — they must fuse.',
 'grammar', 'grammar', 'type', 'pronomi_combinati',
 '{}',
 'Le (to her) + lo fuse as glielo: gliel''ho detto. The forms gli and le both become glie- in combined pronouns; le l''ho is never grammatical in modern Italian.',
 'seed'),
('aabbccdd-4444-4006-0005-b20000000000', 'sentence_construction', 8,
 'Build the Italian sentence: ''Can you send it to me tomorrow?'' (it = la mail)',
 'Me la puoi mandare domani', ARRAY['Domani me la puoi mandare'], NULL,
 'Combined pronouns go before the conjugated modal verb.',
 'grammar', 'grammar', 'tap', 'pronomi_combinati',
 '{}',
 'Mi → me before la (the email): me la. With a modal + infinitive, the pronouns either precede the modal (me la puoi mandare) or attach to the infinitive (puoi mandarmela).',
 'seed'),
('aabbccdd-4444-4006-0005-b20000000000', 'translate_to_target', 9,
 'Translate to Italian: I will give it to you tomorrow. (it = il libro)',
 'Te lo do domani', ARRAY['Te lo darò domani','Io te lo darò domani','Te lo dò domani','Domani te lo do','Domani te lo darò'], NULL,
 'Combine ti + lo; Italian can use the present for near-future promises.',
 'grammar', 'grammar', 'type', 'pronomi_combinati',
 '{}',
 'Ti + lo → te lo, placed before the verb. For a near-future promise Italian uses either the present (te lo do domani) or the future (te lo darò domani).',
 'seed');

-- ─── Lesson 6: Review & Test (mixed) ───────────────────────────

UPDATE lessons
SET title = 'Review & Test',
    description = 'Mixed practice across all five B2 topics: subjunctive, hypotheticals, passive, reported speech and combined pronouns.'
WHERE id = 'aabbccdd-4444-4006-0006-b20000000000';

DELETE FROM exercises WHERE lesson_id = 'aabbccdd-4444-4006-0006-b20000000000';

INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, source_type) VALUES
('aabbccdd-4444-4006-0006-b20000000000', 'multiple_choice', 0,
 'Choose the correct form: Non penso che loro ___ la situazione.',
 'capiscano', '{}', ARRAY['capiscano','hanno capito','stanno capendo','avevano capito'],
 'Verbs of doubt take the subjunctive.',
 'grammar', 'grammar', 'tap', 'congiuntivo_presente',
 ARRAY['hanno capito','stanno capendo','avevano capito'],
 'Non penso che demands the subjunctive: capiscano, with the -isc- infix kept in the plural. Indicative forms (hanno capito, stanno capendo) are the typical error after verbs of doubt.',
 'seed'),
('aabbccdd-4444-4006-0006-b20000000000', 'multiple_choice', 1,
 'Choose the pair that fills both blanks: Se ___ prima, non ___ il treno.',
 'fossimo partiti / avremmo perso', '{}', ARRAY['fossimo partiti / avremmo perso','saremmo partiti / avessimo perso','partiremmo / perdiamo','avremmo partito / fossimo persi'],
 'Unreal past condition: trapassato subjunctive, then past conditional.',
 'grammar', 'grammar', 'tap', 'periodo_ipotetico',
 ARRAY['saremmo partiti / avessimo perso','partiremmo / perdiamo','avremmo partito / fossimo persi'],
 'An unreal past condition takes se + congiuntivo trapassato (fossimo partiti) with the condizionale passato in the main clause (avremmo perso). Swapping the two moods is the classic trap.',
 'seed'),
('aabbccdd-4444-4006-0006-b20000000000', 'fill_blank', 2,
 'Questi palazzi ___ costruiti negli anni Trenta.',
 'furono', ARRAY['sono stati','vennero'], NULL,
 'Historical passive: passato remoto or passato prossimo of essere/venire.',
 'grammar', 'grammar', 'type', 'passivo',
 '{}',
 'Historical passive: furono costruiti (passato remoto) or sono stati costruiti. Venire also works in simple tenses: vennero costruiti. The participle agrees with palazzi: costruiti.',
 'seed'),
('aabbccdd-4444-4006-0006-b20000000000', 'cloze_deletion', 3,
 'Paolo ha detto che ___ stanco e che voleva dormire.',
 'era', '{}', NULL,
 'Match the backshifted tense of voleva.',
 'grammar', 'grammar', 'type', 'discorso_indiretto',
 '{}',
 'Reported speech after ha detto backshifts the present to the imperfect: era, parallel to voleva in the second clause. The direct words were: sono stanco e voglio dormire.',
 'seed'),
('aabbccdd-4444-4006-0006-b20000000000', 'word_form', 4,
 'Sarebbe meglio che tu ___ (rimanere) a casa stasera.',
 'rimanessi', '{}', NULL,
 'A conditional main verb calls for the imperfect subjunctive.',
 'grammar', 'grammar', 'type', 'congiuntivo_imperfetto',
 '{}',
 'After a conditional main clause (sarebbe meglio che), the subordinate takes the imperfect subjunctive: rimanessi. This mood sequence is fixed: never the present subjunctive rimanga here.',
 'seed'),
('aabbccdd-4444-4006-0006-b20000000000', 'fill_blank', 5,
 'Hai restituito i libri a Chiara? — Sì, ___ ho restituiti ieri. (pronome combinato)',
 'glieli', '{}', NULL,
 'Combine ''a Chiara'' (gli) + ''i libri'' (li) into one word.',
 'grammar', 'grammar', 'type', 'pronomi_combinati',
 '{}',
 'A Chiara → glie-, i libri → li: glieli, written as one word. The participle agrees with the preceding direct pronoun li: restituiti, masculine plural.',
 'seed'),
('aabbccdd-4444-4006-0006-b20000000000', 'sentence_transformation', 6,
 'Rewrite in the passive voice: Molti turisti visitano il Colosseo ogni anno.',
 'Il Colosseo è visitato da molti turisti ogni anno', ARRAY['Il Colosseo viene visitato da molti turisti ogni anno','Ogni anno il Colosseo è visitato da molti turisti','Ogni anno il Colosseo viene visitato da molti turisti','Il Colosseo è visitato ogni anno da molti turisti','Il Colosseo viene visitato ogni anno da molti turisti'], NULL,
 'The object becomes the subject; keep the present tense.',
 'grammar', 'grammar', 'type', 'passivo',
 '{}',
 'Il Colosseo becomes the subject; visitano becomes è (or viene) visitato, agreeing with the masculine singular subject; the agent takes da: da molti turisti.',
 'seed'),
('aabbccdd-4444-4006-0006-b20000000000', 'error_correction', 7,
 'Credo che Marco viene alla festa con noi.',
 'Credo che Marco venga alla festa con noi', ARRAY['Credo che Marco venga alla festa con noi.'], NULL,
 'Check the mood after credere che.',
 'grammar', 'grammar', 'type', 'congiuntivo_presente',
 '{}',
 'Credere che requires the subjunctive: venga, not the indicative viene. Venire has an irregular subjunctive stem: venga, veniamo, vengano.',
 'seed'),
('aabbccdd-4444-4006-0006-b20000000000', 'sentence_construction', 8,
 'Build the Italian sentence: ''Marta said that she would call us the next day.''',
 'Marta ha detto che ci avrebbe chiamato il giorno dopo', ARRAY['Marta ha detto che il giorno dopo ci avrebbe chiamato'], NULL,
 'Would call = past conditional; tomorrow shifts to il giorno dopo.',
 'grammar', 'grammar', 'tap', 'discorso_indiretto',
 '{}',
 'A reported future takes the condizionale passato: ci avrebbe chiamato. The time word also shifts: domani becomes il giorno dopo when reporting from the past.',
 'seed'),
('aabbccdd-4444-4006-0006-b20000000000', 'translate_to_target', 9,
 'Translate to Italian: If I had known it, I would have told you.',
 'Se l''avessi saputo, te l''avrei detto', ARRAY['Se lo avessi saputo, te lo avrei detto','Se l''avessi saputo te l''avrei detto','Se l''avessi saputo, te lo avrei detto','Se lo avessi saputo, te l''avrei detto'], NULL,
 'Unreal past: trapassato subjunctive + past conditional, with combined pronouns.',
 'grammar', 'grammar', 'type', 'periodo_ipotetico',
 '{}',
 'Unreal past condition: se + congiuntivo trapassato (l''avessi saputo) and condizionale passato (te l''avrei detto). Ti + lo → te lo, elided to te l'' before avrei.',
 'seed');

-- ═══════════════════════════════════════════════════════════════
-- Grammar rules reference set — Italian (language = 'it')
-- 5 rules per CEFR level: A1, A2, B1, B2.
-- examples/common_errors shapes match components/lesson/RuleCard.tsx
-- (examples: [{target, native}], common_errors: [{error, correction, note}]).
-- ═══════════════════════════════════════════════════════════════

INSERT INTO grammar_rules (language, cefr_level, rule_name, title, explanation, examples, common_errors, tags) VALUES
-- ── A1 ──
('it', 'A1', 'articoli_determinativi', 'Definite Articles (il, la, lo, l'', i, le, gli)',
 'The word for "the" matches the noun''s gender, number and first sound: il libro, lo studente, la casa, l''amico. Plurals: i libri, gli studenti, le case. Use lo/gli before s+consonant, z, gn, ps.',
 '[{"target": "il ragazzo, i ragazzi", "native": "the boy, the boys"}, {"target": "lo zaino, gli zaini", "native": "the backpack, the backpacks"}, {"target": "l''amica, le amiche", "native": "the (female) friend, the friends"}]'::jsonb,
 '[{"error": "il studente", "correction": "lo studente", "note": "Before s + consonant, use lo, not il."}, {"error": "gli case", "correction": "le case", "note": "Feminine plural always takes le."}]'::jsonb,
 ARRAY['articles','gender','nouns']),
('it', 'A1', 'genere_dei_nomi', 'Noun Gender (-o / -a)',
 'Most Italian nouns ending in -o are masculine (il libro) and most ending in -a are feminine (la casa). Nouns in -e can be either: il fiore, la notte. Adjectives and articles must match the noun''s gender.',
 '[{"target": "il tavolo nero", "native": "the black table"}, {"target": "la sedia nera", "native": "the black chair"}, {"target": "la notte lunga", "native": "the long night"}]'::jsonb,
 '[{"error": "la problema", "correction": "il problema", "note": "Greek-origin nouns in -ma are masculine: il problema, il sistema."}]'::jsonb,
 ARRAY['gender','nouns']),
('it', 'A1', 'presente_indicativo', 'Present Tense (-are, -ere, -ire)',
 'Drop the infinitive ending and add person endings: parlo, parli, parla, parliamo, parlate, parlano. -ere verbs use -o, -i, -e, -iamo, -ete, -ono. Some -ire verbs add -isc-: finisco, finisci.',
 '[{"target": "Parlo italiano.", "native": "I speak Italian."}, {"target": "Marco legge un libro.", "native": "Marco reads a book."}, {"target": "Finisco alle sei.", "native": "I finish at six."}]'::jsonb,
 '[{"error": "io parlare italiano", "correction": "io parlo italiano", "note": "Conjugate the verb; don''t use the infinitive as in ''I speak''."}]'::jsonb,
 ARRAY['present-tense','conjugation','verbs']),
('it', 'A1', 'essere_vs_avere', 'Essere vs. Avere (to be vs. to have)',
 'Essere describes identity and states: sono italiano, è tardi. Avere means to have, but Italian uses it in fixed expressions where English uses "to be": ho fame (I am hungry), ho vent''anni (I am twenty).',
 '[{"target": "Ho diciannove anni.", "native": "I am nineteen years old."}, {"target": "Abbiamo sete.", "native": "We are thirsty."}, {"target": "Sono stanco.", "native": "I am tired."}]'::jsonb,
 '[{"error": "Sono vent''anni.", "correction": "Ho vent''anni.", "note": "Age uses avere in Italian: literally ''I have twenty years''."}]'::jsonb,
 ARRAY['essere','avere','expressions']),
('it', 'A1', 'plurale_dei_nomi', 'Plural of Nouns',
 'To form plurals, change the final vowel: -o → -i (libro → libri), -a → -e (casa → case), -e → -i (fiore → fiori). Nouns ending in an accented vowel or a consonant don''t change: la città → le città, il bar → i bar.',
 '[{"target": "un gelato, due gelati", "native": "one ice cream, two ice creams"}, {"target": "una pizza, due pizze", "native": "one pizza, two pizzas"}, {"target": "una città, due città", "native": "one city, two cities"}]'::jsonb,
 '[{"error": "due cittàs", "correction": "due città", "note": "Never add -s; accented nouns are invariable."}]'::jsonb,
 ARRAY['plural','nouns']),
-- ── A2 ──
('it', 'A2', 'passato_prossimo', 'Passato Prossimo (Present Perfect)',
 'The main past tense: present of avere or essere + past participle. Movement and change-of-state verbs take essere, and the participle agrees with the subject: Maria è andata. Most other verbs take avere: ho mangiato.',
 '[{"target": "Ho mangiato una pizza.", "native": "I ate a pizza."}, {"target": "Maria è andata a Roma.", "native": "Maria went to Rome."}, {"target": "Siamo arrivati tardi.", "native": "We arrived late."}]'::jsonb,
 '[{"error": "Ho andato al cinema.", "correction": "Sono andato al cinema.", "note": "Andare takes essere, and the participle agrees with the subject."}]'::jsonb,
 ARRAY['past-tense','auxiliaries','participle']),
('it', 'A2', 'imperfetto', 'The Imperfect (Imperfetto)',
 'Use the imperfetto for past descriptions, habits and ongoing situations: da bambino giocavo a calcio. It contrasts with the passato prossimo, which reports completed events: mentre dormivo, è arrivato Marco.',
 '[{"target": "Da bambino giocavo a calcio.", "native": "As a child I used to play football."}, {"target": "Mentre dormivo, è arrivato Marco.", "native": "While I was sleeping, Marco arrived."}]'::jsonb,
 '[{"error": "Da piccolo ho avuto sempre fame.", "correction": "Da piccolo avevo sempre fame.", "note": "Habitual ''always/used to'' situations take the imperfetto."}]'::jsonb,
 ARRAY['past-tense','imperfetto','aspect']),
('it', 'A2', 'preposizioni_articolate', 'Combined Prepositions (del, alla, nei...)',
 'The prepositions di, a, da, in, su fuse with the definite article: di + il = del, a + la = alla, in + i = nei, su + lo = sullo. Con and per normally stay separate: con il, per la.',
 '[{"target": "Vado alla stazione.", "native": "I''m going to the station."}, {"target": "Il libro dello studente.", "native": "The student''s book."}, {"target": "Le chiavi sono nella borsa.", "native": "The keys are in the bag."}]'::jsonb,
 '[{"error": "Vado a la stazione.", "correction": "Vado alla stazione.", "note": "A + la must fuse into alla."}]'::jsonb,
 ARRAY['prepositions','articles']),
('it', 'A2', 'pronomi_diretti', 'Direct Object Pronouns (lo, la, li, le)',
 'Replace direct objects with lo (him/it), la (her/it), li (them, masc.), le (them, fem.), placed before the conjugated verb: Compri il pane? Sì, lo compro. Before a vowel, lo/la elide: l''ho visto.',
 '[{"target": "Vedi Marco? Sì, lo vedo.", "native": "Do you see Marco? Yes, I see him."}, {"target": "Compro le mele e le mangio.", "native": "I buy the apples and eat them."}]'::jsonb,
 '[{"error": "Sì, vedo lo.", "correction": "Sì, lo vedo.", "note": "Object pronouns go before the conjugated verb, not after."}]'::jsonb,
 ARRAY['pronouns','direct-object','word-order']),
('it', 'A2', 'futuro_semplice', 'Simple Future (Futuro Semplice)',
 'Add future endings to the infinitive stem: parlerò, parlerai, parlerà... -are verbs change a to e: parlare → parlerò. Common irregular stems: andare → andrò, avere → avrò, essere → sarò, venire → verrò.',
 '[{"target": "Domani parlerò con il professore.", "native": "Tomorrow I will speak with the professor."}, {"target": "L''anno prossimo andremo in Italia.", "native": "Next year we will go to Italy."}]'::jsonb,
 '[{"error": "Domani andarò a Roma.", "correction": "Domani andrò a Roma.", "note": "Andare has the irregular future stem andr-."}]'::jsonb,
 ARRAY['future-tense','conjugation']),
-- ── B1 ──
('it', 'B1', 'condizionale_presente', 'Present Conditional (Condizionale)',
 'Formed on the future stem + -ei, -esti, -ebbe, -emmo, -este, -ebbero: parlerei, vorrei, sarei. Use it for polite requests (vorrei un caffè), advice (dovresti riposare) and hypothetical outcomes (comprerei una casa).',
 '[{"target": "Vorrei un caffè, per favore.", "native": "I would like a coffee, please."}, {"target": "Al posto tuo, dovresti riposare.", "native": "In your place, you should rest."}]'::jsonb,
 '[{"error": "Voglio un caffè. (in a bar, abruptly)", "correction": "Vorrei un caffè.", "note": "The conditional softens requests; voglio can sound rude."}]'::jsonb,
 ARRAY['conditional','politeness']),
('it', 'B1', 'imperativo', 'The Imperative (Commands)',
 'Tu-commands: parla!, prendi!, dormi! — but -are verbs flip to -a. Negative tu-command = non + infinitive: non parlare! Formal Lei uses subjunctive forms: parli!, prenda! Pronouns attach to informal commands: dimmelo!',
 '[{"target": "Ascolta bene!", "native": "Listen carefully!"}, {"target": "Non preoccuparti!", "native": "Don''t worry!"}, {"target": "Mi dica, signora.", "native": "Tell me, madam. (formal)"}]'::jsonb,
 '[{"error": "Non parla così forte!", "correction": "Non parlare così forte!", "note": "Negative tu-commands use non + infinitive."}]'::jsonb,
 ARRAY['imperative','commands','pronouns']),
('it', 'B1', 'ci_e_ne', 'The Particles Ci and Ne',
 'Ci replaces a place or a + thing: Vai a Roma? Sì, ci vado. Ne replaces di + thing or a quantity''s source: Quante mele vuoi? Ne voglio due. With quantities, ne is obligatory, unlike English "of them".',
 '[{"target": "Sei mai stato a Napoli? Sì, ci sono stato.", "native": "Have you ever been to Naples? Yes, I''ve been there."}, {"target": "Hai dei libri? Ne ho molti.", "native": "Do you have books? I have many (of them)."}]'::jsonb,
 '[{"error": "Quanti fratelli hai? Ho due.", "correction": "Ne ho due.", "note": "With numbers and quantities, ne cannot be dropped."}]'::jsonb,
 ARRAY['ci','ne','particles','pronouns']),
('it', 'B1', 'trapassato_prossimo', 'Past Perfect (Trapassato Prossimo)',
 'Imperfect of avere/essere + past participle: avevo mangiato, ero partito. It places one past action before another: Quando sono arrivato, il treno era già partito. Essential for reported speech backshift at B2.',
 '[{"target": "Quando sono arrivato, il treno era già partito.", "native": "When I arrived, the train had already left."}, {"target": "Non avevo mai visto quel film.", "native": "I had never seen that film."}]'::jsonb,
 '[{"error": "Quando sono arrivato, il treno è già partito.", "correction": "...il treno era già partito.", "note": "The earlier of two past events takes the trapassato."}]'::jsonb,
 ARRAY['past-tense','trapassato','sequence-of-tenses']),
('it', 'B1', 'pronomi_relativi', 'Relative Pronouns (che, cui)',
 'Che is the all-purpose relative pronoun for subjects and direct objects: il libro che leggo. After a preposition, use cui: la ragazza con cui esco, il motivo per cui parto. Il/la quale is a formal alternative.',
 '[{"target": "Il film che abbiamo visto era bellissimo.", "native": "The film that we saw was beautiful."}, {"target": "L''amico a cui ho scritto vive a Milano.", "native": "The friend I wrote to lives in Milan."}]'::jsonb,
 '[{"error": "la ragazza con che esco", "correction": "la ragazza con cui esco", "note": "After a preposition, che must become cui."}]'::jsonb,
 ARRAY['relative-clauses','pronouns']),
-- ── B2 ──
('it', 'B2', 'congiuntivo', 'The Subjunctive (Il Congiuntivo)',
 'Used after verbs of opinion, emotion, doubt and impersonal expressions: penso che sia, temo che abbia perso, benché fosse. Present/past subjunctive follow a present main verb; the imperfect follows a past or conditional one: volevo che venissi.',
 '[{"target": "Penso che Luca abbia ragione.", "native": "I think Luca is right."}, {"target": "Benché sia tardi, esco.", "native": "Although it is late, I''m going out."}, {"target": "Volevo che tu venissi.", "native": "I wanted you to come."}]'::jsonb,
 '[{"error": "Penso che Luca ha ragione.", "correction": "Penso che Luca abbia ragione.", "note": "Opinion verbs + che require the subjunctive, not the indicative."}]'::jsonb,
 ARRAY['subjunctive','mood','opinion-verbs']),
('it', 'B2', 'periodo_ipotetico', 'Hypothetical Sentences (Periodo Ipotetico)',
 'Real: se piove, resto (indicative). Unreal present: se + imperfect subjunctive + conditional — se fossi ricco, viaggerei. Unreal past: se + trapassato subjunctive + past conditional — se avessi studiato, avrei superato l''esame. Never use the conditional after se.',
 '[{"target": "Se fossi in te, accetterei.", "native": "If I were you, I would accept."}, {"target": "Se avessi saputo, te l''avrei detto.", "native": "If I had known, I would have told you."}]'::jsonb,
 '[{"error": "Se sarei ricco, viaggerei.", "correction": "Se fossi ricco, viaggerei.", "note": "The conditional never follows se; use the imperfect subjunctive."}]'::jsonb,
 ARRAY['conditionals','subjunctive','hypotheticals']),
('it', 'B2', 'passivo_e_si_passivante', 'Passive Voice & Si Passivante',
 'Passive: essere + past participle, agent with da — la legge è approvata dal governo. Venire replaces essere in simple tenses: viene approvata. For general statements Italian prefers the si passivante, where the verb agrees with the noun: si vendono libri.',
 '[{"target": "Il palazzo fu costruito nel 1930.", "native": "The building was built in 1930."}, {"target": "In Italia si beve molto caffè.", "native": "In Italy a lot of coffee is drunk."}, {"target": "Si vendono case in centro.", "native": "Houses are for sale downtown."}]'::jsonb,
 '[{"error": "Si vende molte case.", "correction": "Si vendono molte case.", "note": "With si passivante, the verb agrees with the plural noun."}]'::jsonb,
 ARRAY['passive','si-passivante','agreement']),
('it', 'B2', 'discorso_indiretto', 'Reported Speech (Discorso Indiretto)',
 'After a past reporting verb, tenses backshift: present → imperfect (sono → era), passato prossimo → trapassato (ho perso → aveva perso), future → past conditional (verrò → sarebbe venuto). Time and place words shift too: domani → il giorno dopo, qui → lì.',
 '[{"target": "Ha detto che era stanco.", "native": "He said he was tired."}, {"target": "Ha promesso che sarebbe venuta il giorno dopo.", "native": "She promised she would come the next day."}]'::jsonb,
 '[{"error": "Ha detto che verrà il giorno dopo.", "correction": "Ha detto che sarebbe venuto il giorno dopo.", "note": "A future reported from the past takes the condizionale passato."}]'::jsonb,
 ARRAY['reported-speech','sequence-of-tenses','backshift']),
('it', 'B2', 'pronomi_combinati', 'Combined Pronouns (Pronomi Combinati)',
 'Indirect + direct pronouns fuse before the verb: mi/ti/ci/vi become me/te/ce/ve (me lo presti), and gli/le both become glie-, written as one word: glielo, gliela, glieli, gliele. The past participle agrees with the direct pronoun: gliel''ho data.',
 '[{"target": "Me lo presti?", "native": "Will you lend it to me?"}, {"target": "Gliel''ho detto ieri.", "native": "I told him/her (it) yesterday."}, {"target": "Te le mando domani.", "native": "I''ll send them to you tomorrow."}]'::jsonb,
 '[{"error": "Gli lo do domani.", "correction": "Glielo do domani.", "note": "Gli + lo must fuse into one word: glielo."}]'::jsonb,
 ARRAY['pronouns','combined-pronouns','word-order'])
ON CONFLICT (language, rule_name) DO UPDATE SET
  cefr_level = EXCLUDED.cefr_level,
  title = EXCLUDED.title,
  explanation = EXCLUDED.explanation,
  examples = EXCLUDED.examples,
  common_errors = EXCLUDED.common_errors,
  tags = EXCLUDED.tags;

COMMIT;
