-- ═══════════════════════════════════════════════════════════════
-- Fluenci seed: Chinese (zh) B2 "Complex Grammar" unit rebuild
-- + grammar_rules reference set for zh (A1-B2).
--
-- STAGED SEED — review before applying. Replaces the incorrect
-- European-template lessons (Subjunctive Mood, Complex Tenses, …)
-- with real upper-intermediate Mandarin grammar (HSK 4-5):
-- 把-construction, 被-passives, verb complements, aspect 了/着/过,
-- comparisons, plus a mixed Review & Test lesson.
--
-- All distractors, error sentences and tile permutations were
-- machine-checked against lib/grading.ts fuzzy matching (edit
-- distance <=1 for answers <=4 chars, <=2 otherwise) so no wrong
-- answer is accidentally accepted.
--
-- Apply via Supabase MCP/dashboard. Never db reset / db push.
-- ═══════════════════════════════════════════════════════════════

BEGIN;

UPDATE units SET
  title = 'Complex Grammar',
  description = '把 and 被 sentences, verb complements, aspect particles 了/着/过, and comparisons (HSK 4-5)'
WHERE id = 'aabbccdd-8888-4006-0000-b20000000000';

-- ─── The 把 Construction ───
UPDATE lessons SET title = 'The 把 Construction', description = 'Move the object before the verb with 把 to say what was done to it' WHERE id = 'aabbccdd-8888-4006-0001-b20000000000';
DELETE FROM exercises WHERE lesson_id = 'aabbccdd-8888-4006-0001-b20000000000';
INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, metadata, source_type) VALUES
  ('aabbccdd-8888-4006-0001-b20000000000', 'multiple_choice', 0, 'What does 我把作业写完了 mean?', 'I finished writing my homework.', '{}'::text[], ARRAY['I finished writing my homework.','I want to start my homework.','My homework was too difficult.','I forgot to hand in my homework.']::text[], '把 (bǎ) moves the object before the verb; 写完了 = finished writing.', 'grammar', 'grammar', 'tap', 'ba_construction', ARRAY['I want to start my homework.','My homework was too difficult.','I forgot to hand in my homework.']::text[], 'In a 把-sentence the object (作业) moves before the verb, and the verb carries a result: 写完了 means finished writing. 把 highlights what was done to the homework.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0001-b20000000000', 'multiple_choice', 1, 'Choose the correct sentence: ''Mom cleaned the room until it was spotless.''', '妈妈把房间打扫干净了', '{}'::text[], ARRAY['妈妈把房间打扫干净了','妈妈把打扫干净了房间','妈妈打扫干净了把房间','房间把妈妈打扫干净了']::text[], 'Pattern: Subject + 把 + object + verb + result.', 'grammar', 'grammar', 'tap', 'ba_construction', ARRAY['妈妈把打扫干净了房间','妈妈打扫干净了把房间','房间把妈妈打扫干净了']::text[], 'The 把-pattern is Subject + 把 + object + verb + result: 妈妈把房间打扫干净了. The object 房间 must come right after 把 and before the verb, and the doer stays before 把.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0001-b20000000000', 'fill_blank', 2, '她把衣服洗___了。(She washed the clothes clean.)', '干净', '{}'::text[], NULL, '''clean'' = 干净 (gānjìng), a result stated after the verb 洗.', 'grammar', 'grammar', 'type', 'ba_construction', '{}'::text[], 'A resultative complement after the verb states the outcome: 洗干净 = wash clean. 把 requires the verb to carry a result like this — a bare verb cannot end a 把-sentence.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0001-b20000000000', 'cloze_deletion', 3, '我们把会议___到下星期了。(We postponed the meeting to next week.)', '推迟', ARRAY['延迟','延期']::text[], NULL, '''to postpone'' = 推迟 (tuīchí).', 'grammar', 'grammar', 'type', 'ba_construction', '{}'::text[], '把 + 会议 + 推迟到…: the verb 推迟 plus 到 + time shows what happened to the meeting — it was pushed to next week. The 到-phrase is the required complement.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0001-b20000000000', 'multiple_choice', 4, 'Choose the correct sentence: ''You can''t take this book out of the library.''', '你不能把这本书带出图书馆', '{}'::text[], ARRAY['你不能把这本书带出图书馆','你把这本书不能带出图书馆','这本书不能把你带出图书馆','你不能把带出这本书图书馆']::text[], 'Modals and negation (不能) go BEFORE 把.', 'grammar', 'grammar', 'tap', 'ba_construction', ARRAY['你把这本书不能带出图书馆','这本书不能把你带出图书馆','你不能把带出这本书图书馆']::text[], 'Modal verbs and negation always precede 把, never sit between 把 and the verb: 不能把这本书带出图书馆. Placing 不能 after the 把-phrase is ungrammatical.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0001-b20000000000', 'sentence_construction', 5, 'Arrange the words: ''We have already packed the luggage.''', '我们 已经 把行李 收拾好了', '{}'::text[], NULL, 'The adverb 已经 (yǐjīng) comes before 把.', 'grammar', 'grammar', 'tap', 'ba_construction', '{}'::text[], 'Adverbs like 已经 precede the 把-phrase, and the verb 收拾 carries the result 好了: 我们已经把行李收拾好了.', '{"tiles":["我们","已经","把行李","收拾好了"]}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0001-b20000000000', 'sentence_transformation', 6, 'Rewrite using 把: 我关了窗户。', '我把窗户关了', ARRAY['我把窗户关了。','我把窗户关上了','我把窗户关上了。','我把窗户关好了','我把窗户关好了。']::text[], NULL, '我 + 把 + 窗户 + verb + 了/complement.', 'grammar', 'grammar', 'type', 'ba_construction', '{}'::text[], 'Move the object 窗户 after 把 and put the verb last: 我把窗户关了 (or 关上了). The verb must keep 了 or take a result like 上.', '{"originalSentence":"我关了窗户。","instruction":"Rewrite the sentence using 把."}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0001-b20000000000', 'error_correction', 7, 'Find and fix the error: 他把喝完了那杯茶。', '他把那杯茶喝完了', ARRAY['他把那杯茶喝完了。']::text[], NULL, 'Keep 把. The object (那杯茶) comes right after 把, before the verb.', 'grammar', 'grammar', 'type', 'ba_construction', '{}'::text[], 'In a 把-sentence the object must directly follow 把 and precede the verb: 他把那杯茶喝完了. The verb phrase 喝完了 can never come between 把 and its object.', '{"error_sentence":"他把喝完了那杯茶。"}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0001-b20000000000', 'sentence_construction', 8, 'Arrange the words: ''Please write your name on this piece of paper.''', '请把 你的名字 写在 这张纸上', '{}'::text[], NULL, '请把 + object + 写在 + place.', 'grammar', 'grammar', 'tap', 'ba_construction', '{}'::text[], '把 fronts the object 你的名字, and 写在 + place states where it ends up: 请把你的名字写在这张纸上. The location phrase after 在 is the required complement.', '{"tiles":["请把","你的名字","写在","这张纸上"]}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0001-b20000000000', 'translate_to_target', 9, 'Translate to Chinese using 把: ''Please open the door.''', '请把门打开', ARRAY['请把门打开。','把门打开','把门打开。','请你把门打开','请你把门打开。']::text[], NULL, '请 + 把 + 门 + 打开 (dǎkāi).', 'grammar', 'grammar', 'type', 'ba_construction', '{}'::text[], '把 fronts the object 门, and 打开 (verb + result 开) says what happens to it: 请把门打开. A bare 开 alone cannot end the 把-sentence.', '{}'::jsonb, 'manual');

-- ─── Passives with 被 ───
UPDATE lessons SET title = 'Passives with 被', description = 'Express what happened to things with 被, 让/叫, and the bare (unmarked) passive' WHERE id = 'aabbccdd-8888-4006-0002-b20000000000';
DELETE FROM exercises WHERE lesson_id = 'aabbccdd-8888-4006-0002-b20000000000';
INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, metadata, source_type) VALUES
  ('aabbccdd-8888-4006-0002-b20000000000', 'multiple_choice', 0, 'What does 我的自行车被人偷走了 mean?', 'My bicycle was stolen.', '{}'::text[], ARRAY['My bicycle was stolen.','I stole someone''s bicycle.','My bicycle broke down.','Someone lent me a bicycle.']::text[], '被 (bèi) marks the passive: receiver + 被 + (agent) + verb.', 'grammar', 'grammar', 'tap', 'bei_passive', ARRAY['I stole someone''s bicycle.','My bicycle broke down.','Someone lent me a bicycle.']::text[], '被 marks a passive: 我的自行车 (my bike) is the receiver, 人 is the agent, 偷走了 is what happened to it. So: my bicycle was stolen (by someone).', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0002-b20000000000', 'multiple_choice', 1, 'Choose the correct passive sentence: ''The cake was eaten up by my little brother.''', '蛋糕被弟弟吃完了', '{}'::text[], ARRAY['蛋糕被弟弟吃完了','蛋糕被吃完了弟弟','弟弟被蛋糕吃完了','蛋糕吃完了被弟弟']::text[], 'Receiver + 被 + agent + verb + result.', 'grammar', 'grammar', 'tap', 'bei_passive', ARRAY['蛋糕被吃完了弟弟','弟弟被蛋糕吃完了','蛋糕吃完了被弟弟']::text[], 'The passive order is receiver + 被 + agent + verb + result: 蛋糕被弟弟吃完了. The agent 弟弟 sits between 被 and the verb, never after the verb.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0002-b20000000000', 'multiple_choice', 2, 'What does 信已经寄出去了 mean?', 'The letter has already been sent out.', '{}'::text[], ARRAY['The letter has already been sent out.','I am about to send the letter.','The letter was returned to me.','Someone forgot to send the letter.']::text[], 'An unmarked (notional) passive — no 被 needed.', 'grammar', 'grammar', 'tap', 'bei_passive', ARRAY['I am about to send the letter.','The letter was returned to me.','Someone forgot to send the letter.']::text[], 'Chinese often omits 被 when the subject is a thing and no agent is mentioned: 信寄出去了 = the letter got sent out. This "notional passive" is the most natural choice here.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0002-b20000000000', 'multiple_choice', 3, '我的伞___拿走了。(My umbrella was taken away by someone.) Choose the missing word.', '被人', '{}'::text[], ARRAY['被人','让','叫','把']::text[], '被人 (bèi rén) = "by someone". Bare 让/叫 would need a stated agent.', 'grammar', 'grammar', 'tap', 'bei_passive', ARRAY['让','叫','把']::text[], '被 introduces the agent; with an unknown agent use 被人 (or colloquial 让人/叫人). 让 and 叫 must have their agent stated, so bare 让/叫 cannot fill the blank — only 被 can drop the agent.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0002-b20000000000', 'cloze_deletion', 4, '他被公司___了。(He was fired by the company.)', '解雇', ARRAY['开除','辞退']::text[], NULL, '''to fire, dismiss'' = 解雇 (jiěgù) or 开除 (kāichú).', 'grammar', 'grammar', 'type', 'bei_passive', '{}'::text[], '被 + agent (公司) + verb: 他被公司解雇了 = he was dismissed by the company. The verb after 被 usually takes 了 or another complement.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0002-b20000000000', 'sentence_construction', 5, 'Arrange the words: ''My phone was broken by my little sister.''', '我的手机 被妹妹 弄坏了', '{}'::text[], NULL, 'Receiver first, then 被 + agent, then the verb.', 'grammar', 'grammar', 'tap', 'bei_passive', '{}'::text[], 'Passive order: receiver (我的手机) + 被 + agent (妹妹) + verb + result (弄坏了). The thing affected starts the sentence.', '{"tiles":["我的手机","被妹妹","弄坏了"]}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0002-b20000000000', 'sentence_transformation', 6, 'Rewrite with 被: 警察抓住了小偷。', '小偷被警察抓住了', ARRAY['小偷被警察抓住了。']::text[], NULL, 'Start with 小偷 (the one affected), then 被警察.', 'grammar', 'grammar', 'type', 'bei_passive', '{}'::text[], 'To form the passive, the receiver 小偷 moves to the front and the agent 警察 follows 被: 小偷被警察抓住了. The verb keeps its result complement 住.', '{"originalSentence":"警察抓住了小偷。","instruction":"Rewrite as a passive sentence with 被."}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0002-b20000000000', 'error_correction', 7, 'Find and fix the error: 被小偷偷走了我的钱包。', '我的钱包被小偷偷走了', ARRAY['我的钱包被小偷偷走了。']::text[], NULL, 'Start with the thing affected (我的钱包), then 被 + agent + verb.', 'grammar', 'grammar', 'type', 'bei_passive', '{}'::text[], 'A 被-sentence must begin with the receiver: 我的钱包被小偷偷走了. The affected noun cannot appear after the verb as in English word order.', '{"error_sentence":"被小偷偷走了我的钱包。"}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0002-b20000000000', 'translate_to_native', 8, 'Translate to English: 他被老板批评了一顿。', 'He was criticized by his boss.', ARRAY['He got criticized by his boss.','He was scolded by his boss.','He got scolded by his boss.','He was criticized by the boss.','He was scolded by the boss.','He was told off by his boss.','His boss criticized him.','His boss scolded him.','The boss criticized him.','The boss scolded him.']::text[], NULL, '批评 (pīpíng) = to criticize; 一顿 = a (good) telling-off.', 'grammar', 'grammar', 'type', 'bei_passive', '{}'::text[], '被老板批评了一顿 = was given a scolding by the boss. 一顿 is a verbal measure word for events like scoldings or meals.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0002-b20000000000', 'translate_to_target', 9, 'Translate to Chinese WITHOUT 被 (unmarked passive): ''The clothes have been washed.''', '衣服洗好了', ARRAY['衣服洗好了。','衣服洗完了','衣服洗完了。','衣服已经洗好了','衣服已经洗好了。','衣服洗干净了','衣服洗干净了。']::text[], NULL, '衣服 + 洗 + result (好/完). No 被 needed.', 'grammar', 'grammar', 'type', 'bei_passive', '{}'::text[], 'With an inanimate topic and a verb + result, Chinese prefers the unmarked passive: 衣服洗好了. Adding 被 here would sound unnatural.', '{}'::jsonb, 'manual');

-- ─── Verb Complements ───
UPDATE lessons SET title = 'Verb Complements', description = 'Results (听懂, 找到), directions (拿出来), and possibility (吃不完)' WHERE id = 'aabbccdd-8888-4006-0003-b20000000000';
DELETE FROM exercises WHERE lesson_id = 'aabbccdd-8888-4006-0003-b20000000000';
INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, metadata, source_type) VALUES
  ('aabbccdd-8888-4006-0003-b20000000000', 'multiple_choice', 0, 'What does 我听懂了老师的话 mean?', 'I understood what the teacher said.', '{}'::text[], ARRAY['I understood what the teacher said.','I listened but did not understand the teacher.','I am listening to the teacher right now.','The teacher did not hear me.']::text[], '听 = listen; 懂 = the RESULT (understand).', 'grammar', 'grammar', 'tap', 'verb_complements', ARRAY['I listened but did not understand the teacher.','I am listening to the teacher right now.','The teacher did not hear me.']::text[], '懂 after 听 is a resultative complement: 听懂 = listen with the result of understanding. 了 marks that this result was achieved.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0003-b20000000000', 'multiple_choice', 1, 'Choose the correct sentence: ''He took a dictionary out of his schoolbag.''', '他从书包里拿出了一本词典', '{}'::text[], ARRAY['他从书包里拿出了一本词典','他拿出了从书包里一本词典','他从书包里一本词典拿出了','一本词典他从书包里拿出了']::text[], '从 + place + 里 comes before the verb; the object follows 拿出了.', 'grammar', 'grammar', 'tap', 'verb_complements', ARRAY['他拿出了从书包里一本词典','他从书包里一本词典拿出了','一本词典他从书包里拿出了']::text[], 'The source phrase 从书包里 precedes the verb, and the object follows verb + direction: 他从书包里拿出了一本词典. An indefinite object (一本词典) cannot move before the verb.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0003-b20000000000', 'multiple_choice', 2, '听到这个笑话,大家都笑了___。(Hearing the joke, everyone burst out laughing.) Choose the missing word.', '起来', '{}'::text[], ARRAY['起来','下去','进去','过去']::text[], 'V + 起来 (qǐlai) = an action starting up.', 'grammar', 'grammar', 'tap', 'verb_complements', ARRAY['下去','进去','过去']::text[], '起来 after a verb marks the start of an action: 笑了起来 = burst out laughing. 下去 means continuing, and 进去/过去 are literal directions — none fits "started to laugh".', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0003-b20000000000', 'fill_blank', 3, '对不起,我没听___你的问题,请再说一遍。(Sorry, I did not hear your question clearly — please say it again.)', '清楚', '{}'::text[], NULL, '听 + result: 清楚 (qīngchu) = clearly.', 'grammar', 'grammar', 'type', 'verb_complements', '{}'::text[], '清楚 as a resultative complement states the result of listening: 听清楚 = hear clearly. 没 negates the achieved result: 没听清楚 = did not catch it.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0003-b20000000000', 'cloze_deletion', 4, '这部电视剧很有意思,我想继续看___。(This TV series is really interesting — I want to keep watching it.)', '下去', '{}'::text[], NULL, 'V + 下去 (xiàqu) = continue doing something.', 'grammar', 'grammar', 'type', 'verb_complements', '{}'::text[], '下去 after a verb means to carry the action on: 看下去 = keep watching. 起来 would mean starting, and 完 would mean finishing — the sentence says continue.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0003-b20000000000', 'sentence_construction', 5, 'Arrange the words: ''Please bring the photos back tomorrow.''', '请你 明天 把照片 带回来', ARRAY['明天 请你 把照片 带回来']::text[], NULL, 'Time word before the 把-phrase; 带回来 = bring back (toward the speaker).', 'grammar', 'grammar', 'tap', 'verb_complements', '{}'::text[], '回来 after 带 shows direction toward the speaker: 带回来 = bring back here. The time word 明天 goes before the 把-phrase, never after the verb.', '{"tiles":["请你","明天","把照片","带回来"]}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0003-b20000000000', 'sentence_transformation', 6, 'Rewrite with a potential complement (V + 不 + result): 我不能看懂这本书。', '我看不懂这本书', ARRAY['我看不懂这本书。','这本书我看不懂','这本书我看不懂。']::text[], NULL, 'Insert 不 between 看 and 懂.', 'grammar', 'grammar', 'type', 'verb_complements', '{}'::text[], 'Ability tied to a result uses the potential complement, not 能: insert 不 between verb and result — 看不懂 = cannot (manage to) understand by reading.', '{"originalSentence":"我不能看懂这本书。","instruction":"Rewrite using the potential complement (verb + 不 + result)."}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0003-b20000000000', 'error_correction', 7, 'Find and fix the error: 他走进去了教室。', '他走进教室去了', ARRAY['他走进教室去了。']::text[], NULL, 'The place (教室) goes BETWEEN 进 and 去.', 'grammar', 'grammar', 'type', 'verb_complements', '{}'::text[], 'With compound directional complements, a place object splits them: 走进教室去, never 走进去教室. The location must come before 来/去.', '{"error_sentence":"他走进去了教室。"}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0003-b20000000000', 'multiple_choice', 8, 'What does 我今天做不完这些工作 mean?', 'I can''t finish this work today.', '{}'::text[], ARRAY['I can''t finish this work today.','I don''t want to do this work today.','I didn''t do this work today.','I must finish this work today.']::text[], 'V + 不 + 完 = cannot manage to finish.', 'grammar', 'grammar', 'tap', 'verb_complements', ARRAY['I don''t want to do this work today.','I didn''t do this work today.','I must finish this work today.']::text[], '做不完 is a potential complement: unable to reach the result 完 (finish). It expresses inability, not unwillingness or simple negation.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0003-b20000000000', 'translate_to_target', 9, 'Translate to Chinese using 得: ''I can hear (you) clearly.''', '我听得清楚', ARRAY['听得清楚','我听得清楚。','听得清楚。','我听得很清楚','我听得很清楚。']::text[], NULL, '听 + 得 + 清楚 (the positive potential form).', 'grammar', 'grammar', 'type', 'verb_complements', '{}'::text[], 'The positive potential complement inserts 得 between verb and result: 听得清楚 = can hear clearly. Its negative counterpart swaps 得 for 不: 听不清楚.', '{}'::jsonb, 'manual');

-- ─── Aspect: 了, 着, 过 ───
UPDATE lessons SET title = 'Aspect: 了, 着, 过', description = 'Completed actions, ongoing states, and past experiences' WHERE id = 'aabbccdd-8888-4006-0004-b20000000000';
DELETE FROM exercises WHERE lesson_id = 'aabbccdd-8888-4006-0004-b20000000000';
INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, metadata, source_type) VALUES
  ('aabbccdd-8888-4006-0004-b20000000000', 'multiple_choice', 0, 'What does 我去过三次上海 mean?', 'I have been to Shanghai three times.', '{}'::text[], ARRAY['I have been to Shanghai three times.','I am going to Shanghai three times.','I went to Shanghai three days ago.','I will stay in Shanghai for three days.']::text[], 'V + 过 (guo) = past experience, at least once.', 'grammar', 'grammar', 'tap', 'aspect_particles', ARRAY['I am going to Shanghai three times.','I went to Shanghai three days ago.','I will stay in Shanghai for three days.']::text[], '过 marks experience: 去过 = have been (at some point). 三次 counts the experiences. It says nothing about when — only that it happened before.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0004-b20000000000', 'multiple_choice', 1, 'What does 门开着,进来吧 mean?', 'The door is open — come in.', '{}'::text[], ARRAY['The door is open — come in.','Open the door and come in.','The door was opened just now.','Someone is opening the door.']::text[], 'V + 着 (zhe) = an ongoing state.', 'grammar', 'grammar', 'tap', 'aspect_particles', ARRAY['Open the door and come in.','The door was opened just now.','Someone is opening the door.']::text[], '着 marks a continuing state, not an action: 开着 = is (in the state of being) open. It is not a command and not an event happening right now.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0004-b20000000000', 'multiple_choice', 2, '他去了北京 vs 他去过北京 — what is the difference?', '去了 = he went (and may still be there); 去过 = he has been there before.', '{}'::text[], ARRAY['去了 = he went (and may still be there); 去过 = he has been there before.','去了 = he has been there before; 去过 = he went and may still be there.','They mean exactly the same thing.','去了 = he will go soon; 去过 = he is going right now.']::text[], '了 = completed event; 过 = experience.', 'grammar', 'grammar', 'tap', 'aspect_particles', ARRAY['去了 = he has been there before; 去过 = he went and may still be there.','They mean exactly the same thing.','去了 = he will go soon; 去过 = he is going right now.']::text[], '了 reports a completed event (he went — possibly still there); 过 reports a detached past experience (he has been there at least once, and is not there now).', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0004-b20000000000', 'multiple_choice', 3, 'Choose the sentence that describes the STATE: ''She is wearing a red coat today.''', '她今天穿着一件红大衣', '{}'::text[], ARRAY['她今天穿着一件红大衣','她今天正在穿一件红大衣','她今天要去买一件红大衣','她今天一件红大衣穿着']::text[], '穿着 = the state of wearing; 正在穿 = in the middle of putting on.', 'grammar', 'grammar', 'tap', 'aspect_particles', ARRAY['她今天正在穿一件红大衣','她今天要去买一件红大衣','她今天一件红大衣穿着']::text[], '着 expresses the ongoing state of having something on: 穿着一件红大衣. 正在穿 would mean she is in the act of putting it on, 要去买 is a future purchase (nothing worn yet), and the object cannot move before the verb.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0004-b20000000000', 'sentence_construction', 4, 'Arrange the words: ''A picture is hanging on the wall.''', '墙上 挂着 一幅画', '{}'::text[], NULL, 'Existential pattern: place + V着 + thing.', 'grammar', 'grammar', 'tap', 'aspect_particles', '{}'::text[], 'The existential pattern is place + verb + 着 + thing: 墙上挂着一幅画 = on the wall hangs a picture. 着 marks the lasting state of hanging.', '{"tiles":["墙上","挂着","一幅画"]}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0004-b20000000000', 'sentence_construction', 5, 'Arrange the words: ''We have never eaten Beijing roast duck.''', '我们 从来没 吃过 北京烤鸭', ARRAY['北京烤鸭 我们 从来没 吃过','我们 北京烤鸭 从来没 吃过']::text[], NULL, '从来没 (cónglái méi) + V + 过 = have never done.', 'grammar', 'grammar', 'tap', 'aspect_particles', '{}'::text[], 'Experience is negated with 没 while KEEPING 过: 从来没吃过 = have never eaten. (Contrast 了, which is dropped after 没.)', '{"tiles":["我们","从来没","吃过","北京烤鸭"]}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0004-b20000000000', 'multiple_choice', 6, 'What does 我从来没吃过日本菜 mean?', 'I have never eaten Japanese food.', '{}'::text[], ARRAY['I have never eaten Japanese food.','I have eaten Japanese food only once.','I don''t eat Japanese food anymore.','I didn''t enjoy the Japanese food I ate.']::text[], '从来没 + V + 过 = have never done — 过 is kept under negation.', 'grammar', 'grammar', 'tap', 'aspect_particles', ARRAY['I have eaten Japanese food only once.','I don''t eat Japanese food anymore.','I didn''t enjoy the Japanese food I ate.']::text[], 'Unlike 了, the experiential 过 stays under negation: 从来没吃过 = have never eaten, not even once. 从来 strengthens 没 to "never (in my life)" — it says nothing about habits or how the food tasted.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0004-b20000000000', 'error_correction', 7, 'Find and fix the error: 我以前住过在上海。', '我以前在上海住过', ARRAY['我以前在上海住过。','以前我在上海住过','以前我在上海住过。']::text[], NULL, 'Keep 过. The place phrase 在上海 goes BEFORE the verb.', 'grammar', 'grammar', 'type', 'aspect_particles', '{}'::text[], 'Location phrases with 在 precede the verb: 在上海住过, not 住过在上海. English "lived in Shanghai" order cannot be copied into Chinese.', '{"error_sentence":"我以前住过在上海。"}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0004-b20000000000', 'multiple_choice', 8, 'What does 我学了两年汉语了 mean?', 'I have been learning Chinese for two years and still am.', '{}'::text[], ARRAY['I have been learning Chinese for two years and still am.','I studied Chinese for two years but stopped.','I will study Chinese for two years.','I plan to study Chinese for two more years.']::text[], 'Double 了 = the situation continues up to now.', 'grammar', 'grammar', 'tap', 'aspect_particles', ARRAY['I studied Chinese for two years but stopped.','I will study Chinese for two years.','I plan to study Chinese for two more years.']::text[], 'Verb-了 + duration + sentence-final 了 means the activity has lasted two years AND is still going on. Without the final 了, it could be a finished period.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0004-b20000000000', 'sentence_construction', 9, 'Arrange the words: ''Have you (all) ever seen this movie?''', '你们 看过 这个电影 吗', ARRAY['这个电影 你们 看过 吗','你们 这个电影 看过 吗']::text[], NULL, '看过 (kànguo) = have seen (before); end with 吗.', 'grammar', 'grammar', 'tap', 'aspect_particles', '{}'::text[], 'Asking about experience uses V + 过: 你们看过这个电影吗 = have you (all) ever seen this movie? 了 would ask about a specific completed event instead.', '{"tiles":["你们","看过","这个电影","吗"]}'::jsonb, 'manual');

-- ─── Comparisons ───
UPDATE lessons SET title = 'Comparisons', description = '比, 没有, 不如 and 越来越' WHERE id = 'aabbccdd-8888-4006-0005-b20000000000';
DELETE FROM exercises WHERE lesson_id = 'aabbccdd-8888-4006-0005-b20000000000';
INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, metadata, source_type) VALUES
  ('aabbccdd-8888-4006-0005-b20000000000', 'multiple_choice', 0, 'What does 今天没有昨天热 mean?', 'Today is not as hot as yesterday.', '{}'::text[], ARRAY['Today is not as hot as yesterday.','Today is hotter than yesterday.','Yesterday was not hot at all.','Today and yesterday are equally hot.']::text[], 'A 没有 B + adj = A is not as … as B.', 'grammar', 'grammar', 'tap', 'comparison_structures', ARRAY['Today is hotter than yesterday.','Yesterday was not hot at all.','Today and yesterday are equally hot.']::text[], 'A 没有 B + adjective negates a comparison: 今天没有昨天热 = today does not reach yesterday''s level of heat, i.e. not as hot as yesterday.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0005-b20000000000', 'multiple_choice', 1, 'Choose the correct sentence: ''My older brother is much taller than me.''', '哥哥比我高多了', '{}'::text[], ARRAY['哥哥比我高多了','哥哥比我很高','哥哥很比我高','我比哥哥高多了']::text[], '''Much taller'' = 高多了 / 高得多. Never use 很 in a 比-sentence.', 'grammar', 'grammar', 'tap', 'comparison_structures', ARRAY['哥哥比我很高','哥哥很比我高','我比哥哥高多了']::text[], 'Degree words like 很/非常 are banned in 比-sentences; a big difference is shown AFTER the adjective with 多了 or 得多: 哥哥比我高多了. Reversing 哥哥 and 我 reverses the meaning.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0005-b20000000000', 'multiple_choice', 2, 'What does 这家饭馆不如那家 mean?', 'This restaurant is not as good as that one.', '{}'::text[], ARRAY['This restaurant is not as good as that one.','This restaurant is better than that one.','This restaurant is exactly like that one.','That restaurant has closed down.']::text[], 'A 不如 B = A is not as good as B (好 is implied).', 'grammar', 'grammar', 'tap', 'comparison_structures', ARRAY['This restaurant is better than that one.','This restaurant is exactly like that one.','That restaurant has closed down.']::text[], 'A 不如 B means A falls short of B; with no adjective, 好 is understood: this restaurant is not as good as that one.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0005-b20000000000', 'fill_blank', 3, '天气___热了,夏天快到了。(The weather is getting hotter and hotter — summer is almost here.)', '越来越', '{}'::text[], NULL, '''more and more'' = 越来越 (yuè lái yuè).', 'grammar', 'grammar', 'type', 'comparison_structures', '{}'::text[], '越来越 + adjective = increasingly, more and more: 越来越热 = hotter and hotter. Sentence-final 了 marks this as a developing change.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0005-b20000000000', 'cloze_deletion', 4, '这首歌我越听越___。(The more I listen to this song, the more I like it.)', '喜欢', '{}'::text[], NULL, '越 A 越 B = the more A, the more B; "like" = 喜欢 (xǐhuan).', 'grammar', 'grammar', 'type', 'comparison_structures', '{}'::text[], '越…越… links two increasing quantities: 越听越喜欢 = the more (I) listen, the more (I) like it. Both verbs share the same subject here.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0005-b20000000000', 'sentence_construction', 5, 'Arrange the words: ''Beijing''s winter is much colder than Shanghai''s.''', '北京的冬天 比上海 冷得多', '{}'::text[], NULL, 'A + 比 B + adjective + 得多.', 'grammar', 'grammar', 'tap', 'comparison_structures', '{}'::text[], 'The comparison frame is A + 比 + B + adjective, with the big-difference marker 得多 after the adjective: 北京的冬天比上海冷得多.', '{"tiles":["北京的冬天","比上海","冷得多"]}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0005-b20000000000', 'sentence_transformation', 6, 'Say the same thing starting with 我 and using 没有: 弟弟比我高。', '我没有弟弟高', ARRAY['我没有弟弟高。','我没有弟弟那么高','我没有弟弟那么高。']::text[], NULL, '我 + 没有 + 弟弟 + (那么) + 高.', 'grammar', 'grammar', 'type', 'comparison_structures', '{}'::text[], 'A 比 B + adj flips into B 没有 A + adj: 弟弟比我高 = 我没有弟弟高. 那么 can be added before the adjective for emphasis.', '{"originalSentence":"弟弟比我高。","instruction":"Say the same thing starting with 我, using 没有."}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0005-b20000000000', 'error_correction', 7, 'Find and fix the error: 今天比昨天很冷。', '今天比昨天冷多了', ARRAY['今天比昨天冷多了。','今天比昨天冷得多','今天比昨天冷得多。']::text[], NULL, 'Remove 很; put 多了 (or 得多) AFTER 冷 to say ''much colder''.', 'grammar', 'grammar', 'type', 'comparison_structures', '{}'::text[], '很 can never modify the adjective in a 比-sentence. Degree of difference goes after the adjective: 冷多了 / 冷得多 = much colder.', '{"error_sentence":"今天比昨天很冷。"}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0005-b20000000000', 'multiple_choice', 8, 'Choose the correct sentence: ''My older sister is three years older than my younger brother.''', '姐姐比弟弟大三岁', '{}'::text[], ARRAY['姐姐比弟弟大三岁','弟弟比姐姐大三岁','姐姐大三岁比弟弟','姐姐三岁比弟弟大']::text[], 'The measure (三岁) comes AFTER the adjective 大.', 'grammar', 'grammar', 'tap', 'comparison_structures', ARRAY['弟弟比姐姐大三岁','姐姐大三岁比弟弟','姐姐三岁比弟弟大']::text[], 'Exact differences follow the adjective: 比…大三岁 = three years older. The 比-phrase stays before the adjective, and swapping 姐姐/弟弟 reverses who is older.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0005-b20000000000', 'translate_to_target', 9, 'Translate to Chinese using 越来越: ''Chinese is getting more and more interesting.''', '汉语越来越有意思了', ARRAY['汉语越来越有意思了。','汉语越来越有意思','汉语越来越有意思。','中文越来越有意思了','中文越来越有意思了。','中文越来越有意思','中文越来越有意思。','汉语越来越有趣了','中文越来越有趣了']::text[], NULL, '汉语 + 越来越 + 有意思 (+ 了).', 'grammar', 'grammar', 'type', 'comparison_structures', '{}'::text[], '越来越 precedes the adjective phrase: 汉语越来越有意思了. The final 了 signals a change developing over time.', '{}'::jsonb, 'manual');

-- ─── Review & Test ───
UPDATE lessons SET title = 'Review & Test', description = 'Mixed practice: 把, 被, complements, aspect and comparisons' WHERE id = 'aabbccdd-8888-4006-0006-b20000000000';
DELETE FROM exercises WHERE lesson_id = 'aabbccdd-8888-4006-0006-b20000000000';
INSERT INTO exercises (lesson_id, type, order_index, prompt, correct_answer, accepted_answers, options, hint_text, skill_type, subskill, response_mode, target_grammar, distractors, explanation, metadata, source_type) VALUES
  ('aabbccdd-8888-4006-0006-b20000000000', 'multiple_choice', 0, 'What does 请把手机关掉 mean?', 'Please turn off your phone.', '{}'::text[], ARRAY['Please turn off your phone.','Please answer your phone.','Please buy a new phone.','Please lend me your phone.']::text[], '把 + 手机 + 关掉 (guāndiào) = switch it off.', 'grammar', 'grammar', 'tap', 'ba_construction', ARRAY['Please answer your phone.','Please buy a new phone.','Please lend me your phone.']::text[], '把 fronts the object 手机, and 关掉 (verb + result 掉) says what to do with it: switch it off completely.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0006-b20000000000', 'multiple_choice', 1, 'Choose the correct sentence: ''The homework was taken away by the teacher.''', '作业被老师拿走了', '{}'::text[], ARRAY['作业被老师拿走了','作业被拿走了老师','老师被作业拿走了','作业拿走了被老师']::text[], 'Receiver + 被 + agent + verb + result.', 'grammar', 'grammar', 'tap', 'bei_passive', ARRAY['作业被拿走了老师','老师被作业拿走了','作业拿走了被老师']::text[], 'Passive order: 作业 (receiver) + 被 + 老师 (agent) + 拿走了 (verb + result). The agent must sit between 被 and the verb.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0006-b20000000000', 'multiple_choice', 2, 'What does 我看不懂这篇文章 mean?', 'I can''t understand this article.', '{}'::text[], ARRAY['I can''t understand this article.','I don''t want to read this article.','I haven''t read this article yet.','This article is not interesting.']::text[], '看 + 不 + 懂 = read without managing to understand.', 'grammar', 'grammar', 'tap', 'verb_complements', ARRAY['I don''t want to read this article.','I haven''t read this article yet.','This article is not interesting.']::text[], '看不懂 is a potential complement: unable to achieve the result 懂 by reading. It expresses inability, not preference or simple negation.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0006-b20000000000', 'multiple_choice', 3, 'What does 桌子上放着一本书 mean?', 'There is a book (lying) on the table.', '{}'::text[], ARRAY['There is a book (lying) on the table.','Someone is putting a book on the table right now.','The book was taken off the table.','I put a book on the table yesterday.']::text[], 'Place + V着 + thing = an existing state.', 'grammar', 'grammar', 'tap', 'aspect_particles', ARRAY['Someone is putting a book on the table right now.','The book was taken off the table.','I put a book on the table yesterday.']::text[], '放着 with 着 describes a lasting state — the book sits there. It is not an action in progress and not a past event.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0006-b20000000000', 'cloze_deletion', 4, '我的中文___他好,他学了十年了。(My Chinese is not as good as his — he has studied for ten years.)', '不如', ARRAY['没有']::text[], NULL, '''not as good as'' = 不如 (bùrú) or 没有.', 'grammar', 'grammar', 'type', 'comparison_structures', '{}'::text[], 'A 不如 B (+adj) = A is not as good as B; 没有 works the same way here. 比 would wrongly claim my Chinese is BETTER than his.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0006-b20000000000', 'fill_blank', 5, '外面太吵了,我听不___你说的话。(It is too noisy outside — I cannot hear what you are saying clearly.)', '清楚', '{}'::text[], NULL, '听不 + 清楚 (qīngchu) = cannot hear clearly.', 'grammar', 'grammar', 'type', 'verb_complements', '{}'::text[], 'The potential negative inserts 不 between verb and result: 听不清楚 = cannot manage to hear clearly, because of the noise.', '{}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0006-b20000000000', 'sentence_construction', 6, 'Arrange the words: ''Please move these chairs downstairs.''', '请把 这些椅子 搬到 楼下去', '{}'::text[], NULL, '请把 + object + 搬到 + place + 去.', 'grammar', 'grammar', 'tap', 'ba_construction', '{}'::text[], '把 fronts 这些椅子, and 搬到…去 shows the result and direction of the move: 请把这些椅子搬到楼下去.', '{"tiles":["请把","这些椅子","搬到","楼下去"]}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0006-b20000000000', 'sentence_transformation', 7, 'Rewrite with 被: 妹妹吃完了那块蛋糕。', '那块蛋糕被妹妹吃完了', ARRAY['那块蛋糕被妹妹吃完了。']::text[], NULL, 'Start with 那块蛋糕, then 被妹妹.', 'grammar', 'grammar', 'type', 'bei_passive', '{}'::text[], 'The receiver 那块蛋糕 moves to the front; the agent 妹妹 follows 被; the verb keeps its result: 那块蛋糕被妹妹吃完了.', '{"originalSentence":"妹妹吃完了那块蛋糕。","instruction":"Rewrite as a passive sentence with 被."}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0006-b20000000000', 'error_correction', 8, 'Find and fix the error: 这个房间比那个很大。', '这个房间比那个大多了', ARRAY['这个房间比那个大多了。','这个房间比那个大得多','这个房间比那个大得多。']::text[], NULL, 'Remove 很; add 多了 (or 得多) after 大 for ''much bigger''.', 'grammar', 'grammar', 'type', 'comparison_structures', '{}'::text[], '很 is not allowed before the adjective in a 比-sentence. To say "much bigger", put 多了 or 得多 after 大: 比那个大多了.', '{"error_sentence":"这个房间比那个很大。"}'::jsonb, 'manual'),
  ('aabbccdd-8888-4006-0006-b20000000000', 'sentence_construction', 9, 'Arrange the words: ''I have never seen this movie.''', '我 从来没 看过 这个电影', ARRAY['这个电影 我 从来没 看过','我 这个电影 从来没 看过']::text[], NULL, '从来没 + 看过 — 过 stays under negation.', 'grammar', 'grammar', 'tap', 'aspect_particles', '{}'::text[], 'Negated experience keeps 过: 我从来没看过这个电影 = I have never seen this movie. 从来 strengthens 没 to "never".', '{"tiles":["我","从来没","看过","这个电影"]}'::jsonb, 'manual');

-- ─── Grammar rules reference set (zh, A1-B2) ───
INSERT INTO grammar_rules (language, cefr_level, rule_name, title, explanation, examples, common_errors, tags) VALUES
  ('zh', 'A1', 'shi_sentences', 'The verb 是 (to be)', '是 (shì) links two nouns: A 是 B. Negate it with 不是. Unlike English "be", 是 is NOT used before adjectives — say 我很忙, not 我是忙.', '[{"target":"他是学生。(Tā shì xuésheng.)","native":"He is a student."},{"target":"这不是我的书。(Zhè bú shì wǒ de shū.)","native":"This is not my book."}]'::jsonb, '[{"error":"她是很漂亮。","correction":"她很漂亮。","note":"Do not use 是 before an adjective."},{"error":"这是不我的书。","correction":"这不是我的书。","note":"不 goes directly before 是."}]'::jsonb, ARRAY['hsk1','copula','shi']::text[]),
  ('zh', 'A1', 'you_possession', '有 for possession and existence', '有 (yǒu) means "to have" or "there is/are". It is always negated with 没, never 不: 我没有时间 = I have no time.', '[{"target":"我有两个哥哥。(Wǒ yǒu liǎng ge gēge.)","native":"I have two older brothers."},{"target":"桌子上有一杯茶。(Zhuōzi shang yǒu yì bēi chá.)","native":"There is a cup of tea on the table."}]'::jsonb, '[{"error":"我不有钱。","correction":"我没有钱。","note":"有 is negated with 没, not 不."},{"error":"桌子上有那本书。","correction":"那本书在桌子上。","note":"有 introduces new or indefinite things; definite ones use 在."}]'::jsonb, ARRAY['hsk1','you','existence']::text[]),
  ('zh', 'A1', 'svo_word_order', 'Basic word order', 'Chinese is Subject + Time + Place + Verb + Object. Time and place expressions come BEFORE the verb, not at the end as in English.', '[{"target":"我们晚上在饭馆吃饭。(Wǒmen wǎnshang zài fànguǎn chīfàn.)","native":"We eat at a restaurant in the evening."},{"target":"我明天去北京。(Wǒ míngtiān qù Běijīng.)","native":"I am going to Beijing tomorrow."}]'::jsonb, '[{"error":"我去北京明天。","correction":"我明天去北京。","note":"Time words go before the verb."},{"error":"他学习在图书馆。","correction":"他在图书馆学习。","note":"Place phrases with 在 go before the verb."}]'::jsonb, ARRAY['hsk1','word_order']::text[]),
  ('zh', 'A1', 'measure_words', 'Measure words', 'A number or 这/那 needs a measure word before the noun: 三本书 (three books), 一杯咖啡 (a cup of coffee). 个 (ge) is the general-purpose measure word.', '[{"target":"我买了三本书。(Wǒ mǎi le sān běn shū.)","native":"I bought three books."},{"target":"那个人是我的老师。(Nà ge rén shì wǒ de lǎoshī.)","native":"That person is my teacher."}]'::jsonb, '[{"error":"我有三书。","correction":"我有三本书。","note":"A measure word is required between number and noun."},{"error":"一个书","correction":"一本书","note":"Books take 本, not 个."}]'::jsonb, ARRAY['hsk1','measure_words','classifiers']::text[]),
  ('zh', 'A1', 'ma_questions', 'Questions with 吗 and 呢', 'Add 吗 to a statement to make a yes/no question — word order does not change. 呢 bounces a question back: 我很好,你呢? Question words like 什么 never combine with 吗.', '[{"target":"你是美国人吗?(Nǐ shì Měiguórén ma?)","native":"Are you American?"},{"target":"我很好,你呢?(Wǒ hěn hǎo, nǐ ne?)","native":"I am fine — and you?"}]'::jsonb, '[{"error":"你叫什么名字吗?","correction":"你叫什么名字?","note":"吗 cannot be used with a question word like 什么."},{"error":"吗你是老师?","correction":"你是老师吗?","note":"吗 always goes at the end."}]'::jsonb, ARRAY['hsk1','questions','particles']::text[]),
  ('zh', 'A2', 'le_completion', 'Completion 了', 'Verb + 了 marks a completed or realized action — it is not a past tense: 吃了饭再走 = leave after eating. With the negative 没(有), 了 is dropped.', '[{"target":"我买了一本书。(Wǒ mǎi le yì běn shū.)","native":"I bought a book."},{"target":"他没来。(Tā méi lái.)","native":"He did not come."}]'::jsonb, '[{"error":"我昨天没去了商店。","correction":"我昨天没去商店。","note":"了 is dropped after 没."},{"error":"我明天吃了饭。","correction":"我明天吃饭。","note":"Do not add 了 to a plain future statement."}]'::jsonb, ARRAY['hsk2','aspect','le']::text[]),
  ('zh', 'A2', 'guo_experiential', 'Experiential 过', 'Verb + 过 (guo) means the subject has had that experience at least once: 我去过中国 = I have been to China. Negation is 没(有) + V + 过 — 过 is KEPT.', '[{"target":"我去过中国两次。(Wǒ qùguo Zhōngguó liǎng cì.)","native":"I have been to China twice."},{"target":"他从来没吃过烤鸭。(Tā cónglái méi chīguo kǎoyā.)","native":"He has never eaten roast duck."}]'::jsonb, '[{"error":"我从来没吃烤鸭。","correction":"我从来没吃过烤鸭。","note":"Keep 过 when negating an experience."},{"error":"我去过北京去年。","correction":"我去年去过北京。","note":"Time words still go before the verb."}]'::jsonb, ARRAY['hsk2','aspect','guo']::text[]),
  ('zh', 'A2', 'zai_progressive', 'Progressive 在 / 正在', '在 or 正在 before the verb marks an action in progress: 他正在打电话 = he is on the phone right now. Use 着 instead for lasting states like wearing or hanging.', '[{"target":"他正在打电话呢。(Tā zhèngzài dǎ diànhuà ne.)","native":"He is making a phone call right now."},{"target":"我在做饭。(Wǒ zài zuòfàn.)","native":"I am cooking."}]'::jsonb, '[{"error":"他正在穿着一件大衣。","correction":"他穿着一件大衣。","note":"A state uses 着 alone, not 正在 + 着."},{"error":"我是吃饭。","correction":"我在吃饭。","note":"Use 在, not 是, for ongoing actions."}]'::jsonb, ARRAY['hsk2','aspect','progressive']::text[]),
  ('zh', 'A2', 'modal_verbs', 'Modal verbs 会, 能, 可以', '会 = learned skill (我会游泳); 能 = physical ability or possibility; 可以 = permission. All are negated with 不 and come before the main verb.', '[{"target":"我会说一点儿汉语。(Wǒ huì shuō yìdiǎnr Hànyǔ.)","native":"I can speak a little Chinese."},{"target":"这里不能抽烟。(Zhèli bù néng chōuyān.)","native":"You cannot smoke here."}]'::jsonb, '[{"error":"我会去游泳吗?(asking permission)","correction":"我可以去游泳吗?","note":"Permission uses 可以, not 会."},{"error":"他病了,不可以来上课。","correction":"他病了,不能来上课。","note":"Inability due to circumstances uses 能, not 可以."}]'::jsonb, ARRAY['hsk2','modals']::text[]),
  ('zh', 'A2', 'basic_comparison_bi', 'Basic comparison with 比', 'A 比 B + adjective = A is more … than B: 今天比昨天冷. Never put 很/非常 before the adjective in a 比-sentence.', '[{"target":"今天比昨天冷。(Jīntiān bǐ zuótiān lěng.)","native":"Today is colder than yesterday."},{"target":"他比我大。(Tā bǐ wǒ dà.)","native":"He is older than me."}]'::jsonb, '[{"error":"他比我很高。","correction":"他比我高。","note":"No 很 before the adjective in 比-sentences."},{"error":"他很比我高。","correction":"他比我高。","note":"很 cannot modify the 比-phrase either."}]'::jsonb, ARRAY['hsk3','comparison','bi']::text[]),
  ('zh', 'B1', 'shi_de_construction', 'Emphasis with 是……的', 'For past events, 是……的 highlights the time, place or manner: 我是昨天来的 = it was yesterday that I came. 是 is optional in positive sentences but required in the negative 不是……的.', '[{"target":"他是坐飞机来的。(Tā shì zuò fēijī lái de.)","native":"He came by plane (that is how he came)."},{"target":"你是在哪儿学的汉语?(Nǐ shì zài nǎr xué de Hànyǔ?)","native":"Where did you learn Chinese?"}]'::jsonb, '[{"error":"我是昨天来了。","correction":"我是昨天来的。","note":"是…pairs with 的, not with 了."},{"error":"他不昨天来的。","correction":"他不是昨天来的。","note":"The negative requires 不是."}]'::jsonb, ARRAY['hsk3','emphasis','shi_de']::text[]),
  ('zh', 'B1', 'zhe_durative', 'Durative 着', 'Verb + 着 (zhe) marks a continuing state or background action: 门开着 = the door is open; 他笑着说 = he said, smiling. It describes states, not events.', '[{"target":"墙上挂着一张地图。(Qiáng shang guàzhe yì zhāng dìtú.)","native":"A map is hanging on the wall."},{"target":"他笑着回答了问题。(Tā xiàozhe huídá le wèntí.)","native":"He answered the question with a smile."}]'::jsonb, '[{"error":"墙上挂一张地图。","correction":"墙上挂着一张地图。","note":"The existential place + verb pattern needs 着 to mark the lasting state."},{"error":"门开着了。","correction":"门开着。","note":"着 and 了 do not stack on a simple state."}]'::jsonb, ARRAY['hsk3','aspect','zhe']::text[]),
  ('zh', 'B1', 'directional_complements', 'Directional complements', 'V + 来/去 shows movement toward or away from the speaker; compounds add direction: 拿出来, 走进去, 爬上来. A place object splits the compound: 走进教室去.', '[{"target":"他从包里拿出一本词典来。(Tā cóng bāo li ná chū yì běn cídiǎn lái.)","native":"He took a dictionary out of the bag."},{"target":"我们走进教室去了。(Wǒmen zǒujìn jiàoshì qu le.)","native":"We walked into the classroom."}]'::jsonb, '[{"error":"他走进去了教室。","correction":"他走进教室去了。","note":"The place goes between 进 and 去."},{"error":"请拿来出那本书。","correction":"请把那本书拿出来。","note":"The compound is 出来, in that order."}]'::jsonb, ARRAY['hsk3','complements','direction']::text[]),
  ('zh', 'B1', 'duration_complement', 'Duration of time', 'How long an action lasts goes AFTER the verb: 我学了两年汉语. With sentence-final 了 as well (学了两年了), the activity continues up to now.', '[{"target":"我学了两年汉语。(Wǒ xué le liǎng nián Hànyǔ.)","native":"I studied Chinese for two years."},{"target":"我学汉语学了两年了。(Wǒ xué Hànyǔ xué le liǎng nián le.)","native":"I have been studying Chinese for two years (and still am)."}]'::jsonb, '[{"error":"我两年学了汉语。","correction":"我学了两年汉语。","note":"Duration follows the verb."},{"error":"他等你三个小时在门口。","correction":"他在门口等了你三个小时。","note":"Place before the verb, duration after it."}]'::jsonb, ARRAY['hsk3','duration','complements']::text[]),
  ('zh', 'B1', 'separable_verbs', 'Separable verbs (离合词)', 'Verb-object compounds like 见面, 结婚, 睡觉 split to host 了/过 or duration: 结过婚, 睡了八个小时的觉. They cannot take another object directly — say 跟他见面, not 见面他.', '[{"target":"我们见过面。(Wǒmen jiànguo miàn.)","native":"We have met before."},{"target":"他睡了八个小时的觉。(Tā shuì le bā ge xiǎoshí de jiào.)","native":"He slept for eight hours."}]'::jsonb, '[{"error":"我想见面你。","correction":"我想跟你见面。","note":"Separable verbs cannot take a direct object."},{"error":"他结婚过。","correction":"他结过婚。","note":"过 goes inside the compound: 结过婚."}]'::jsonb, ARRAY['hsk4','separable_verbs']::text[]),
  ('zh', 'B2', 'ba_construction', 'The 把 construction', 'Subject + 把 + object + verb + result: 请把门关上. The object must be specific, and the verb cannot stand bare — it needs 了 or a complement. Negation and modals go BEFORE 把.', '[{"target":"请把门关上。(Qǐng bǎ mén guānshang.)","native":"Please close the door."},{"target":"我没把作业带来。(Wǒ méi bǎ zuòyè dàilai.)","native":"I did not bring my homework."}]'::jsonb, '[{"error":"他把咖啡喝。","correction":"他把咖啡喝完了。","note":"The verb needs a result or 了 after it."},{"error":"我把没书带来。","correction":"我没把书带来。","note":"没 goes before 把."}]'::jsonb, ARRAY['hsk4','ba','word_order']::text[]),
  ('zh', 'B2', 'bei_passive', 'Passives with 被 / 让 / 叫', 'Receiver + 被 (+agent) + verb + complement: 车被(人)偷走了. 让 and 叫 are colloquial but must state the agent. Everyday Chinese often prefers the unmarked passive: 饭做好了.', '[{"target":"我的自行车被人偷走了。(Wǒ de zìxíngchē bèi rén tōuzǒu le.)","native":"My bicycle was stolen."},{"target":"饭做好了。(Fàn zuòhǎo le.)","native":"The food is ready (has been cooked)."}]'::jsonb, '[{"error":"蛋糕叫吃完了。","correction":"蛋糕叫弟弟吃完了。","note":"让/叫 require the agent to be stated."},{"error":"被小偷偷走了我的钱包。","correction":"我的钱包被小偷偷走了。","note":"The receiver starts the sentence."}]'::jsonb, ARRAY['hsk4','bei','passive']::text[]),
  ('zh', 'B2', 'verb_complements', 'Result & potential complements', 'A result follows the verb: 听懂, 找到, 写错. Insert 得/不 between them for possibility: 听得懂 = can understand, 听不懂 = cannot. Use this potential form, not 能/不能, for ability tied to a result.', '[{"target":"我听不懂粤语。(Wǒ tīng bu dǒng Yuèyǔ.)","native":"I cannot understand Cantonese."},{"target":"这么多菜我们吃不完。(Zhème duō cài wǒmen chī bu wán.)","native":"We cannot finish this much food."}]'::jsonb, '[{"error":"我不能听懂。","correction":"我听不懂。","note":"Use the potential form V不C, not 不能 + VC."},{"error":"我找不到了我的手机。","correction":"我找不到我的手机。","note":"The potential form does not take 了."}]'::jsonb, ARRAY['hsk4','complements','potential']::text[]),
  ('zh', 'B2', 'aspect_particles', 'Aspect: 了, 着, 过 contrasted', '了 = completed event (他去了北京); 着 = ongoing state (门开着); 过 = past experience (他去过北京). Under 没-negation, 了 is dropped but 过 is kept. 学了两年了 = still ongoing.', '[{"target":"他去了北京。/ 他去过北京。(qù le / qùguo)","native":"He went to Beijing. / He has been to Beijing."},{"target":"门开着,进来吧。(Mén kāizhe, jìnlai ba.)","native":"The door is open — come in."}]'::jsonb, '[{"error":"我没吃了早饭。","correction":"我没吃早饭。","note":"了 is dropped after 没."},{"error":"我没去过北京了。","correction":"我没去过北京。","note":"过 is kept, but no 了 with 没."}]'::jsonb, ARRAY['hsk4','aspect','le','zhe','guo']::text[]),
  ('zh', 'B2', 'comparison_structures', 'Comparison structures', 'A 比 B + adj (+ 得多/多了/一点儿): 他比我大三岁 — the measure follows the adjective. Negatives: A 没有 B (那么) adj, or A 不如 B (+adj). 越来越 + adj = more and more. Never use 很 before the adjective.', '[{"target":"他比我大三岁。(Tā bǐ wǒ dà sān suì.)","native":"He is three years older than me."},{"target":"天气越来越热了。(Tiānqì yuè lái yuè rè le.)","native":"The weather is getting hotter and hotter."}]'::jsonb, '[{"error":"今天比昨天很冷。","correction":"今天比昨天冷多了。","note":"No 很 in 比-sentences; use 多了/得多 after the adjective."},{"error":"他比我大三岁多了。","correction":"他比我大三岁。","note":"Use either an exact measure or 多了, not both."}]'::jsonb, ARRAY['hsk5','comparison','bi','buru']::text[])
ON CONFLICT (language, rule_name) DO UPDATE SET
  cefr_level = EXCLUDED.cefr_level,
  title = EXCLUDED.title,
  explanation = EXCLUDED.explanation,
  examples = EXCLUDED.examples,
  common_errors = EXCLUDED.common_errors,
  tags = EXCLUDED.tags;

COMMIT;
