// Deno tests for ai-chat response parsing.
//
// Run with: `deno test supabase/functions/ai-chat/parse.test.ts`
//
// The load-bearing assertion in this file is that a response WITHOUT a gloss
// still parses cleanly. The gloss exists to kill a second paid round trip to
// the `translate` function, but it is an optimisation, not a contract the
// client can depend on: the safety fallback has none, a truncated completion
// has none, and a turn generated by an older deployment has none. Every one of
// those must still produce a usable reply — the client simply pays for a
// translate call in that case, exactly as it always did.

import { assert, assertEquals } from 'https://deno.land/std@0.168.0/testing/asserts.ts';
import { MAX_GLOSS_CHARS, normalizeGloss, parseAIResponse } from './parse.ts';

Deno.test('a gloss is surfaced when the model supplies one', () => {
  const parsed = parseAIResponse(JSON.stringify({
    reply: '¡Claro! ¿Qué te gusta cocinar?',
    correction: null,
    vocabularyHighlights: ['cocinar'],
    gloss: 'Of course! What do you like to cook?',
  }));
  assertEquals(parsed.reply, '¡Claro! ¿Qué te gusta cocinar?');
  assertEquals(parsed.gloss, 'Of course! What do you like to cook?');
});

Deno.test('a response WITHOUT a gloss still parses — reply and correction intact', () => {
  // This is the older contract, verbatim. It must keep working: cached and
  // queued turns predate the field entirely.
  const parsed = parseAIResponse(JSON.stringify({
    reply: 'Me gusta el café.',
    correction: {
      shortLabel: 'Missing article',
      explanation: 'Spanish needs the definite article here.',
      original: 'me gusta café',
      corrected: 'me gusta el café',
      errorType: 'grammar',
      severity: 'minor',
      example: null,
    },
    vocabularyHighlights: ['café'],
  }));
  assertEquals(parsed.reply, 'Me gusta el café.');
  assertEquals(parsed.gloss, null, 'a missing gloss must be null, never undefined or ""');
  assert(parsed.correction !== null, 'the rest of the response must survive a missing gloss');
  assertEquals(parsed.correction?.shortLabel, 'Missing article');
  assertEquals(parsed.vocabularyHighlights, ['café']);
});

Deno.test('a null or blank gloss is normalised to null, not shown as an empty caption', () => {
  const explicitNull = parseAIResponse(JSON.stringify({ reply: 'Hola.', gloss: null }));
  assertEquals(explicitNull.gloss, null);

  const blank = parseAIResponse(JSON.stringify({ reply: 'Hola.', gloss: '   \n ' }));
  assertEquals(blank.gloss, null, 'whitespace is not a gloss — it would render as a blank line');

  // A non-string is what a model produces when it decides the field wants
  // structure. Better no gloss than "[object Object]" under the bubble.
  const wrongType = parseAIResponse(JSON.stringify({ reply: 'Hola.', gloss: { en: 'Hi.' } }));
  assertEquals(wrongType.gloss, null);
});

Deno.test('a runaway gloss is capped rather than relayed whole', () => {
  const long = 'x'.repeat(MAX_GLOSS_CHARS + 500);
  const parsed = parseAIResponse(JSON.stringify({ reply: 'Hola.', gloss: long }));
  assert(parsed.gloss !== null);
  assertEquals(parsed.gloss!.length, MAX_GLOSS_CHARS);
});

Deno.test('gloss survives the fenced-code-block and embedded-JSON recovery paths', () => {
  const body = JSON.stringify({ reply: 'Bonjour !', gloss: 'Hello!' });

  const fenced = parseAIResponse('```json\n' + body + '\n```');
  assertEquals(fenced.gloss, 'Hello!');

  const chatty = parseAIResponse('Here you go:\n' + body + '\nHope that helps.');
  assertEquals(chatty.gloss, 'Hello!');
});

Deno.test('pre-JSON output parses with no gloss instead of throwing', () => {
  // The [CORRECTION]: marker format never carried a gloss and never will.
  const parsed = parseAIResponse('Ciao! Come stai?\n[CORRECTION]: "sono bene" should be "sto bene".');
  assertEquals(parsed.reply, 'Ciao! Come stai?');
  assertEquals(parsed.gloss, null);
  assert(parsed.correction !== null);

  // And plain prose with no marker at all.
  const bare = parseAIResponse('Guten Tag!');
  assertEquals(bare.reply, 'Guten Tag!');
  assertEquals(bare.gloss, null);
});

Deno.test('normalizeGloss trims but does not otherwise rewrite', () => {
  assertEquals(normalizeGloss('  I like coffee.  '), 'I like coffee.');
  assertEquals(normalizeGloss(undefined), null);
  assertEquals(normalizeGloss(42), null);
});
