/**
 * Launch splash — the contract between the native launch screen and the
 * in-app animated stage (canvas "Fluenci UI 2.0", page "Splash · A with Sol",
 * board A3 · Peek, picked 2026-09-09).
 *
 * iOS shows a static storyboard until the JS bundle paints; nothing on it can
 * move. So the moment is built in two halves that must be pixel-identical at
 * the seam:
 *
 *   1. The storyboard: the app-icon tile, `TILE_SIZE` points wide, centred on
 *      the scheme's Home ground. Generated by the `expo-splash-screen` plugin
 *      from `app.json` (`imageWidth`, `backgroundColor`, `dark`).
 *   2. `components/splash/LaunchSplash.tsx`: mounts over the app drawing that
 *      same frame, hides the storyboard, then plays — the tile breathes, the
 *      wordmark rises, Sol peeks out from behind the tile and ducks back — and
 *      crossfades into whatever the router has rendered underneath.
 *
 * `launch-splash.test.ts` holds `app.json` to these numbers so the two halves
 * cannot drift apart: if the tile size or a ground colour changes here, the
 * plugin config has to change with it (and the storyboard regenerated).
 *
 * Apple's rules baked in: the static frame carries no text (it cannot be
 * localised), the whole stage stays well under two seconds, it runs on cold
 * start only (the root layout mounts once), and it never waits on the network.
 */

/** Width and height of the app-icon tile, in points, in BOTH halves. */
export const TILE_SIZE = 132;

/** Sol behind the tile: hidden until he moves, so he must fit inside it. */
export const SOL_SIZE = 120;

/** Distance from the tile's bottom edge to the wordmark's top. */
export const WORDMARK_GAP = 22;

/** Wordmark type: Manrope 800, the UI 2.0 heading face, tracked tight. */
export const WORDMARK_FONT_SIZE = 34;
export const WORDMARK_LINE_HEIGHT = 38;
export const WORDMARK_LETTER_SPACING = -1.2;

/** The navy of the app icon; the tile's own fill, not a theme colour. */
export const TILE_FILL = '#00021B';

/** Where Sol's head comes to rest when he peeks (tile-relative points, deg). */
export const PEEK = { x: -58, y: -76, rotate: -14 } as const;
/** The small second look before he ducks back. */
export const TWITCH = { x: -62, y: -70, rotate: -8 } as const;

export interface LaunchSplashPlan {
  /** Tile scale-up then settle, ms each. */
  breatheUp: number;
  breatheDown: number;
  /** Wordmark: wait, then fade/rise. */
  wordDelay: number;
  wordIn: number;
  /** Sol: appear after this, peek out over `peekOut`, hold until `holdUntil`,
   *  twitch for `twitch`, duck back over `peekBack`. All ms from stage start. */
  solDelay: number;
  peekOut: number;
  holdUntil: number;
  twitch: number;
  peekBack: number;
  /** Crossfade into the app: starts at `fadeDelay`, lasts `fade`. */
  fadeDelay: number;
  fade: number;
  /** Whether Sol is drawn at all. */
  sol: boolean;
}

/**
 * The stage's timings. With reduced motion on, nothing travels: the wordmark
 * fades in, the stage fades out, Sol stays home.
 */
export function launchSplashPlan(reduceMotion: boolean): LaunchSplashPlan {
  if (reduceMotion) {
    return {
      breatheUp: 0,
      breatheDown: 0,
      wordDelay: 0,
      wordIn: 300,
      solDelay: 0,
      peekOut: 0,
      holdUntil: 0,
      twitch: 0,
      peekBack: 0,
      fadeDelay: 900,
      fade: 400,
      sol: false,
    };
  }
  return {
    breatheUp: 350,
    breatheDown: 450,
    wordDelay: 300,
    wordIn: 600,
    solDelay: 100,
    peekOut: 350,
    holdUntil: 1000,
    twitch: 150,
    peekBack: 300,
    fadeDelay: 1700,
    fade: 600,
    sol: true,
  };
}

/** When the stage is fully gone and the overlay can unmount, ms. */
export function launchSplashTotalMs(plan: LaunchSplashPlan): number {
  return plan.fadeDelay + plan.fade;
}
